// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/apis/nodemanagement.gke.io/v1alpha1"
)

// FakeUpdateInfos implements UpdateInfoInterface
type FakeUpdateInfos struct {
	Fake *FakeNodemanagementV1alpha1
	ns   string
}

var updateinfosResource = schema.GroupVersionResource{Group: "nodemanagement.gke.io", Version: "v1alpha1", Resource: "updateinfos"}

var updateinfosKind = schema.GroupVersionKind{Group: "nodemanagement.gke.io", Version: "v1alpha1", Kind: "UpdateInfo"}

// Get takes name of the updateInfo, and returns the corresponding updateInfo object, and an error if there is any.
func (c *FakeUpdateInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UpdateInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(updateinfosResource, c.ns, name), &v1alpha1.UpdateInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpdateInfo), err
}

// List takes label and field selectors, and returns the list of UpdateInfos that match those selectors.
func (c *FakeUpdateInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UpdateInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(updateinfosResource, updateinfosKind, c.ns, opts), &v1alpha1.UpdateInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UpdateInfoList{ListMeta: obj.(*v1alpha1.UpdateInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.UpdateInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested updateInfos.
func (c *FakeUpdateInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(updateinfosResource, c.ns, opts))

}

// Create takes the representation of a updateInfo and creates it.  Returns the server's representation of the updateInfo, and an error, if there is any.
func (c *FakeUpdateInfos) Create(ctx context.Context, updateInfo *v1alpha1.UpdateInfo, opts v1.CreateOptions) (result *v1alpha1.UpdateInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(updateinfosResource, c.ns, updateInfo), &v1alpha1.UpdateInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpdateInfo), err
}

// Update takes the representation of a updateInfo and updates it. Returns the server's representation of the updateInfo, and an error, if there is any.
func (c *FakeUpdateInfos) Update(ctx context.Context, updateInfo *v1alpha1.UpdateInfo, opts v1.UpdateOptions) (result *v1alpha1.UpdateInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(updateinfosResource, c.ns, updateInfo), &v1alpha1.UpdateInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpdateInfo), err
}

// Delete takes name of the updateInfo and deletes it. Returns an error if one occurs.
func (c *FakeUpdateInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(updateinfosResource, c.ns, name, opts), &v1alpha1.UpdateInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUpdateInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(updateinfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UpdateInfoList{})
	return err
}

// Patch applies the patch and returns the patched updateInfo.
func (c *FakeUpdateInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpdateInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(updateinfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.UpdateInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UpdateInfo), err
}
