// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/capacityrequests/apis/internal.autoscaling.gke.io/v1alpha1"
)

// FakeCapacityRequests implements CapacityRequestInterface
type FakeCapacityRequests struct {
	Fake *FakeInternalV1alpha1
	ns   string
}

var capacityrequestsResource = schema.GroupVersionResource{Group: "internal.autoscaling.gke.io", Version: "v1alpha1", Resource: "capacityrequests"}

var capacityrequestsKind = schema.GroupVersionKind{Group: "internal.autoscaling.gke.io", Version: "v1alpha1", Kind: "CapacityRequest"}

// Get takes name of the capacityRequest, and returns the corresponding capacityRequest object, and an error if there is any.
func (c *FakeCapacityRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CapacityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(capacityrequestsResource, c.ns, name), &v1alpha1.CapacityRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CapacityRequest), err
}

// List takes label and field selectors, and returns the list of CapacityRequests that match those selectors.
func (c *FakeCapacityRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CapacityRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(capacityrequestsResource, capacityrequestsKind, c.ns, opts), &v1alpha1.CapacityRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CapacityRequestList{ListMeta: obj.(*v1alpha1.CapacityRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.CapacityRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested capacityRequests.
func (c *FakeCapacityRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(capacityrequestsResource, c.ns, opts))

}

// Create takes the representation of a capacityRequest and creates it.  Returns the server's representation of the capacityRequest, and an error, if there is any.
func (c *FakeCapacityRequests) Create(ctx context.Context, capacityRequest *v1alpha1.CapacityRequest, opts v1.CreateOptions) (result *v1alpha1.CapacityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(capacityrequestsResource, c.ns, capacityRequest), &v1alpha1.CapacityRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CapacityRequest), err
}

// Update takes the representation of a capacityRequest and updates it. Returns the server's representation of the capacityRequest, and an error, if there is any.
func (c *FakeCapacityRequests) Update(ctx context.Context, capacityRequest *v1alpha1.CapacityRequest, opts v1.UpdateOptions) (result *v1alpha1.CapacityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(capacityrequestsResource, c.ns, capacityRequest), &v1alpha1.CapacityRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CapacityRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCapacityRequests) UpdateStatus(ctx context.Context, capacityRequest *v1alpha1.CapacityRequest, opts v1.UpdateOptions) (*v1alpha1.CapacityRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(capacityrequestsResource, "status", c.ns, capacityRequest), &v1alpha1.CapacityRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CapacityRequest), err
}

// Delete takes name of the capacityRequest and deletes it. Returns an error if one occurs.
func (c *FakeCapacityRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(capacityrequestsResource, c.ns, name), &v1alpha1.CapacityRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCapacityRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(capacityrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CapacityRequestList{})
	return err
}

// Patch applies the patch and returns the patched capacityRequest.
func (c *FakeCapacityRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CapacityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(capacityrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CapacityRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CapacityRequest), err
}
