// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cloudgooglecomv1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/client/applyconfiguration/cloud.google.com/v1"
	v1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/cloud.google.com/v1"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=cloud.google.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("Accelerator"):
		return &cloudgooglecomv1.AcceleratorApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AcceleratorConfig"):
		return &cloudgooglecomv1.AcceleratorConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AcceleratorSpec"):
		return &cloudgooglecomv1.AcceleratorSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("BootDiskConfig"):
		return &cloudgooglecomv1.BootDiskConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CompactPlacementConfig"):
		return &cloudgooglecomv1.CompactPlacementConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ConfidentialNodeConfig"):
		return &cloudgooglecomv1.ConfidentialNodeConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ConfidentialNodeType"):
		return &cloudgooglecomv1.ConfidentialNodeTypeApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CPUPlatform"):
		return &cloudgooglecomv1.CPUPlatformApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("LocalSSDConfig"):
		return &cloudgooglecomv1.LocalSSDConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineConfig"):
		return &cloudgooglecomv1.MachineConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineConfigSpec"):
		return &cloudgooglecomv1.MachineConfigSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineConfigStatus"):
		return &cloudgooglecomv1.MachineConfigStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineFamily"):
		return &cloudgooglecomv1.MachineFamilyApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineFamilyWeights"):
		return &cloudgooglecomv1.MachineFamilyWeightsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineProperties"):
		return &cloudgooglecomv1.MachinePropertiesApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineResources"):
		return &cloudgooglecomv1.MachineResourcesApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineType"):
		return &cloudgooglecomv1.MachineTypeApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineTypeWeights"):
		return &cloudgooglecomv1.MachineTypeWeightsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PersistentDiskTypeConfig"):
		return &cloudgooglecomv1.PersistentDiskTypeConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ResourceWeights"):
		return &cloudgooglecomv1.ResourceWeightsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("TpuConfig"):
		return &cloudgooglecomv1.TpuConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("UsagePolicy"):
		return &cloudgooglecomv1.UsagePolicyApplyConfiguration{}

	}
	return nil
}
