// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/capacityrequests/apis/internal.autoscaling.gke.io/v1"
	scheme "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/capacityrequests/client/clientset/versioned/scheme"
)

// CapacityRequestsGetter has a method to return a CapacityRequestInterface.
// A group's client should implement this interface.
type CapacityRequestsGetter interface {
	CapacityRequests(namespace string) CapacityRequestInterface
}

// CapacityRequestInterface has methods to work with CapacityRequest resources.
type CapacityRequestInterface interface {
	Create(ctx context.Context, capacityRequest *v1.CapacityRequest, opts metav1.CreateOptions) (*v1.CapacityRequest, error)
	Update(ctx context.Context, capacityRequest *v1.CapacityRequest, opts metav1.UpdateOptions) (*v1.CapacityRequest, error)
	UpdateStatus(ctx context.Context, capacityRequest *v1.CapacityRequest, opts metav1.UpdateOptions) (*v1.CapacityRequest, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CapacityRequest, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CapacityRequestList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CapacityRequest, err error)
	CapacityRequestExpansion
}

// capacityRequests implements CapacityRequestInterface
type capacityRequests struct {
	client rest.Interface
	ns     string
}

// newCapacityRequests returns a CapacityRequests
func newCapacityRequests(c *InternalV1Client, namespace string) *capacityRequests {
	return &capacityRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the capacityRequest, and returns the corresponding capacityRequest object, and an error if there is any.
func (c *capacityRequests) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CapacityRequest, err error) {
	result = &v1.CapacityRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("capacityrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CapacityRequests that match those selectors.
func (c *capacityRequests) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CapacityRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CapacityRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("capacityrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested capacityRequests.
func (c *capacityRequests) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("capacityrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a capacityRequest and creates it.  Returns the server's representation of the capacityRequest, and an error, if there is any.
func (c *capacityRequests) Create(ctx context.Context, capacityRequest *v1.CapacityRequest, opts metav1.CreateOptions) (result *v1.CapacityRequest, err error) {
	result = &v1.CapacityRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("capacityrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(capacityRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a capacityRequest and updates it. Returns the server's representation of the capacityRequest, and an error, if there is any.
func (c *capacityRequests) Update(ctx context.Context, capacityRequest *v1.CapacityRequest, opts metav1.UpdateOptions) (result *v1.CapacityRequest, err error) {
	result = &v1.CapacityRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("capacityrequests").
		Name(capacityRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(capacityRequest).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *capacityRequests) UpdateStatus(ctx context.Context, capacityRequest *v1.CapacityRequest, opts metav1.UpdateOptions) (result *v1.CapacityRequest, err error) {
	result = &v1.CapacityRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("capacityrequests").
		Name(capacityRequest.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(capacityRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the capacityRequest and deletes it. Returns an error if one occurs.
func (c *capacityRequests) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("capacityrequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *capacityRequests) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("capacityrequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched capacityRequest.
func (c *capacityRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CapacityRequest, err error) {
	result = &v1.CapacityRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("capacityrequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
