// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	provisioningxk8siov1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/provisioningrequests/apis/provisioning.x-k8s.io/v1alpha1"
	versioned "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/provisioningrequests/client/clientset/versioned"
	internalinterfaces "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/provisioningrequests/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/provisioningrequests/client/listers/provisioning.x-k8s.io/v1alpha1"
)

// ProvisioningRequestInformer provides access to a shared informer and lister for
// ProvisioningRequests.
type ProvisioningRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ProvisioningRequestLister
}

type provisioningRequestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProvisioningRequestInformer constructs a new informer for ProvisioningRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProvisioningRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProvisioningRequestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProvisioningRequestInformer constructs a new informer for ProvisioningRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProvisioningRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProvisioningV1alpha1().ProvisioningRequests(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProvisioningV1alpha1().ProvisioningRequests(namespace).Watch(context.TODO(), options)
			},
		},
		&provisioningxk8siov1alpha1.ProvisioningRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *provisioningRequestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProvisioningRequestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *provisioningRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&provisioningxk8siov1alpha1.ProvisioningRequest{}, f.defaultInformer)
}

func (f *provisioningRequestInformer) Lister() v1alpha1.ProvisioningRequestLister {
	return v1alpha1.NewProvisioningRequestLister(f.Informer().GetIndexer())
}
