// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/capacityrequests/apis/internal.autoscaling.gke.io/v1alpha1"
)

// CapacityRequestLister helps list CapacityRequests.
// All objects returned here must be treated as read-only.
type CapacityRequestLister interface {
	// List lists all CapacityRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CapacityRequest, err error)
	// CapacityRequests returns an object that can list and get CapacityRequests.
	CapacityRequests(namespace string) CapacityRequestNamespaceLister
	CapacityRequestListerExpansion
}

// capacityRequestLister implements the CapacityRequestLister interface.
type capacityRequestLister struct {
	indexer cache.Indexer
}

// NewCapacityRequestLister returns a new CapacityRequestLister.
func NewCapacityRequestLister(indexer cache.Indexer) CapacityRequestLister {
	return &capacityRequestLister{indexer: indexer}
}

// List lists all CapacityRequests in the indexer.
func (s *capacityRequestLister) List(selector labels.Selector) (ret []*v1alpha1.CapacityRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CapacityRequest))
	})
	return ret, err
}

// CapacityRequests returns an object that can list and get CapacityRequests.
func (s *capacityRequestLister) CapacityRequests(namespace string) CapacityRequestNamespaceLister {
	return capacityRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CapacityRequestNamespaceLister helps list and get CapacityRequests.
// All objects returned here must be treated as read-only.
type CapacityRequestNamespaceLister interface {
	// List lists all CapacityRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CapacityRequest, err error)
	// Get retrieves the CapacityRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.CapacityRequest, error)
	CapacityRequestNamespaceListerExpansion
}

// capacityRequestNamespaceLister implements the CapacityRequestNamespaceLister
// interface.
type capacityRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CapacityRequests in the indexer for a given namespace.
func (s capacityRequestNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.CapacityRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CapacityRequest))
	})
	return ret, err
}

// Get retrieves the CapacityRequest from the indexer for a given namespace and name.
func (s capacityRequestNamespaceLister) Get(name string) (*v1alpha1.CapacityRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("capacityrequest"), name)
	}
	return obj.(*v1alpha1.CapacityRequest), nil
}
