// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file shouldn't be modified directly. Its source of truth is located
// in the GKE codebase:
// cs///depot/google3/cloud/kubernetes/proto/internal.proto
// If you want to change anything, first submit the changes there and get the
// EK team approval, then sync this file and generate the go file using
// "protoc --go_out=. --go_opt=paths=source_relative  --proto_path=. downsize_config.proto"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: pkg/ekvms/processor/proto/downsize_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownsizeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of downsizing behaviors sorted by MaxDesiredSizeFraction.
	Behaviors []*DownsizeConfig_DownsizeBehavior `protobuf:"bytes,1,rep,name=behaviors,proto3" json:"behaviors,omitempty"`
	// Time window duration for applying max function to avoid unnecessary resize patterns.
	SmoothingWindowLength *durationpb.Duration `protobuf:"bytes,2,opt,name=smoothing_window_length,json=smoothingWindowLength,proto3" json:"smoothing_window_length,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DownsizeConfig) Reset() {
	*x = DownsizeConfig{}
	mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownsizeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownsizeConfig) ProtoMessage() {}

func (x *DownsizeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownsizeConfig.ProtoReflect.Descriptor instead.
func (*DownsizeConfig) Descriptor() ([]byte, []int) {
	return file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescGZIP(), []int{0}
}

func (x *DownsizeConfig) GetBehaviors() []*DownsizeConfig_DownsizeBehavior {
	if x != nil {
		return x.Behaviors
	}
	return nil
}

func (x *DownsizeConfig) GetSmoothingWindowLength() *durationpb.Duration {
	if x != nil {
		return x.SmoothingWindowLength
	}
	return nil
}

// DownsizeBehavior defines conditions for downsizing an EK node and whether
// it's a suitable scaledown candidate.
type DownsizeConfig_DownsizeBehavior struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max allowed size fraction for a node relative to its physical maximum size.
	MaxDesiredSizeFraction float64 `protobuf:"fixed64,1,opt,name=max_desired_size_fraction,json=maxDesiredSizeFraction,proto3" json:"max_desired_size_fraction,omitempty"`
	// Minimum allowed size fraction after a downsize.
	MinDownsizeFraction float64 `protobuf:"fixed64,2,opt,name=min_downsize_fraction,json=minDownsizeFraction,proto3" json:"min_downsize_fraction,omitempty"`
	// Delay in duration before a downsize is performed after it's allowed.
	DownsizeDelay *durationpb.Duration `protobuf:"bytes,3,opt,name=downsize_delay,json=downsizeDelay,proto3" json:"downsize_delay,omitempty"`
	// Indicates if the node is a valid scaledown candidate.
	AllowedForScaledown bool `protobuf:"varint,4,opt,name=allowed_for_scaledown,json=allowedForScaledown,proto3" json:"allowed_for_scaledown,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownsizeConfig_DownsizeBehavior) Reset() {
	*x = DownsizeConfig_DownsizeBehavior{}
	mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownsizeConfig_DownsizeBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownsizeConfig_DownsizeBehavior) ProtoMessage() {}

func (x *DownsizeConfig_DownsizeBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownsizeConfig_DownsizeBehavior.ProtoReflect.Descriptor instead.
func (*DownsizeConfig_DownsizeBehavior) Descriptor() ([]byte, []int) {
	return file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DownsizeConfig_DownsizeBehavior) GetMaxDesiredSizeFraction() float64 {
	if x != nil {
		return x.MaxDesiredSizeFraction
	}
	return 0
}

func (x *DownsizeConfig_DownsizeBehavior) GetMinDownsizeFraction() float64 {
	if x != nil {
		return x.MinDownsizeFraction
	}
	return 0
}

func (x *DownsizeConfig_DownsizeBehavior) GetDownsizeDelay() *durationpb.Duration {
	if x != nil {
		return x.DownsizeDelay
	}
	return nil
}

func (x *DownsizeConfig_DownsizeBehavior) GetAllowedForScaledown() bool {
	if x != nil {
		return x.AllowedForScaledown
	}
	return false
}

var File_pkg_ekvms_processor_proto_downsize_config_proto protoreflect.FileDescriptor

const file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc = "" +
	"\n" +
	"/pkg/ekvms/processor/proto/downsize_config.proto\x12\tdownsizer\x1a\x1egoogle/protobuf/duration.proto\"\xa7\x03\n" +
	"\x0eDownsizeConfig\x12H\n" +
	"\tbehaviors\x18\x01 \x03(\v2*.downsizer.DownsizeConfig.DownsizeBehaviorR\tbehaviors\x12Q\n" +
	"\x17smoothing_window_length\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x15smoothingWindowLength\x1a\xf7\x01\n" +
	"\x10DownsizeBehavior\x129\n" +
	"\x19max_desired_size_fraction\x18\x01 \x01(\x01R\x16maxDesiredSizeFraction\x122\n" +
	"\x15min_downsize_fraction\x18\x02 \x01(\x01R\x13minDownsizeFraction\x12@\n" +
	"\x0edownsize_delay\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rdownsizeDelay\x122\n" +
	"\x15allowed_for_scaledown\x18\x04 \x01(\bR\x13allowedForScaledownB\x1dZ\x1b./pkg/ekvms/processor/protob\x06proto3"

var (
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescOnce sync.Once
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData []byte
)

func file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescGZIP() []byte {
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescOnce.Do(func() {
		file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc), len(file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc)))
	})
	return file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData
}

var file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ekvms_processor_proto_downsize_config_proto_goTypes = []any{
	(*DownsizeConfig)(nil),                  // 0: downsizer.DownsizeConfig
	(*DownsizeConfig_DownsizeBehavior)(nil), // 1: downsizer.DownsizeConfig.DownsizeBehavior
	(*durationpb.Duration)(nil),             // 2: google.protobuf.Duration
}
var file_pkg_ekvms_processor_proto_downsize_config_proto_depIdxs = []int32{
	1, // 0: downsizer.DownsizeConfig.behaviors:type_name -> downsizer.DownsizeConfig.DownsizeBehavior
	2, // 1: downsizer.DownsizeConfig.smoothing_window_length:type_name -> google.protobuf.Duration
	2, // 2: downsizer.DownsizeConfig.DownsizeBehavior.downsize_delay:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_ekvms_processor_proto_downsize_config_proto_init() }
func file_pkg_ekvms_processor_proto_downsize_config_proto_init() {
	if File_pkg_ekvms_processor_proto_downsize_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc), len(file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ekvms_processor_proto_downsize_config_proto_goTypes,
		DependencyIndexes: file_pkg_ekvms_processor_proto_downsize_config_proto_depIdxs,
		MessageInfos:      file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes,
	}.Build()
	File_pkg_ekvms_processor_proto_downsize_config_proto = out.File
	file_pkg_ekvms_processor_proto_downsize_config_proto_goTypes = nil
	file_pkg_ekvms_processor_proto_downsize_config_proto_depIdxs = nil
}
