// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file shouldn't be modified directly. Its source of truth is located
// in the GKE codebase.
// If you want to change anything, first submit the changes there and get the
// EK team approval, then sync this file and generate the go file using
// "protoc --go_out=. --go_opt=paths=source_relative  --proto_path=. downsize_config.proto"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: pkg/ekvms/processor/proto/downsize_config.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownsizeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of downsizing behaviors sorted by MaxDesiredSizeFraction.
	Behaviors []*DownsizeConfig_DownsizeBehavior `protobuf:"bytes,1,rep,name=behaviors,proto3" json:"behaviors,omitempty"`
	// Time window duration for applying max function to avoid unnecessary resize patterns.
	SmoothingWindowLength *durationpb.Duration `protobuf:"bytes,2,opt,name=smoothing_window_length,json=smoothingWindowLength,proto3" json:"smoothing_window_length,omitempty"`
}

func (x *DownsizeConfig) Reset() {
	*x = DownsizeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownsizeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownsizeConfig) ProtoMessage() {}

func (x *DownsizeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownsizeConfig.ProtoReflect.Descriptor instead.
func (*DownsizeConfig) Descriptor() ([]byte, []int) {
	return file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescGZIP(), []int{0}
}

func (x *DownsizeConfig) GetBehaviors() []*DownsizeConfig_DownsizeBehavior {
	if x != nil {
		return x.Behaviors
	}
	return nil
}

func (x *DownsizeConfig) GetSmoothingWindowLength() *durationpb.Duration {
	if x != nil {
		return x.SmoothingWindowLength
	}
	return nil
}

// DownsizeBehavior defines conditions for downsizing an EK node and whether
// it's a suitable scaledown candidate.
type DownsizeConfig_DownsizeBehavior struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Max allowed size fraction for a node relative to its physical maximum size.
	MaxDesiredSizeFraction float64 `protobuf:"fixed64,1,opt,name=max_desired_size_fraction,json=maxDesiredSizeFraction,proto3" json:"max_desired_size_fraction,omitempty"`
	// Minimum allowed size fraction after a downsize.
	MinDownsizeFraction float64 `protobuf:"fixed64,2,opt,name=min_downsize_fraction,json=minDownsizeFraction,proto3" json:"min_downsize_fraction,omitempty"`
	// Delay in duration before a downsize is performed after it's allowed.
	DownsizeDelay *durationpb.Duration `protobuf:"bytes,3,opt,name=downsize_delay,json=downsizeDelay,proto3" json:"downsize_delay,omitempty"`
	// Indicates if the node is a valid scaledown candidate.
	AllowedForScaledown bool `protobuf:"varint,4,opt,name=allowed_for_scaledown,json=allowedForScaledown,proto3" json:"allowed_for_scaledown,omitempty"`
}

func (x *DownsizeConfig_DownsizeBehavior) Reset() {
	*x = DownsizeConfig_DownsizeBehavior{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownsizeConfig_DownsizeBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownsizeConfig_DownsizeBehavior) ProtoMessage() {}

func (x *DownsizeConfig_DownsizeBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownsizeConfig_DownsizeBehavior.ProtoReflect.Descriptor instead.
func (*DownsizeConfig_DownsizeBehavior) Descriptor() ([]byte, []int) {
	return file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DownsizeConfig_DownsizeBehavior) GetMaxDesiredSizeFraction() float64 {
	if x != nil {
		return x.MaxDesiredSizeFraction
	}
	return 0
}

func (x *DownsizeConfig_DownsizeBehavior) GetMinDownsizeFraction() float64 {
	if x != nil {
		return x.MinDownsizeFraction
	}
	return 0
}

func (x *DownsizeConfig_DownsizeBehavior) GetDownsizeDelay() *durationpb.Duration {
	if x != nil {
		return x.DownsizeDelay
	}
	return nil
}

func (x *DownsizeConfig_DownsizeBehavior) GetAllowedForScaledown() bool {
	if x != nil {
		return x.AllowedForScaledown
	}
	return false
}

var File_pkg_ekvms_processor_proto_downsize_config_proto protoreflect.FileDescriptor

var file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6b, 0x76, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x77, 0x6e,
	0x73, 0x69, 0x7a, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x72, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x03, 0x0a,
	0x0e, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x48, 0x0a, 0x09, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x09,
	0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x12, 0x51, 0x0a, 0x17, 0x73, 0x6d, 0x6f,
	0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x15, 0x73, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x1a, 0xf7, 0x01, 0x0a,
	0x10, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f,
	0x72, 0x12, 0x39, 0x0a, 0x19, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x16, 0x6d, 0x61, 0x78, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64,
	0x53, 0x69, 0x7a, 0x65, 0x46, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x15,
	0x6d, 0x69, 0x6e, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x66, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x6d, 0x69, 0x6e,
	0x44, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x46, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x40, 0x0a, 0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x64, 0x65, 0x6c,
	0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x66, 0x6f,
	0x72, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x53, 0x63, 0x61,
	0x6c, 0x65, 0x64, 0x6f, 0x77, 0x6e, 0x42, 0x1d, 0x5a, 0x1b, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x65, 0x6b, 0x76, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescOnce sync.Once
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData = file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc
)

func file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescGZIP() []byte {
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescOnce.Do(func() {
		file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData)
	})
	return file_pkg_ekvms_processor_proto_downsize_config_proto_rawDescData
}

var file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ekvms_processor_proto_downsize_config_proto_goTypes = []interface{}{
	(*DownsizeConfig)(nil),                  // 0: downsizer.DownsizeConfig
	(*DownsizeConfig_DownsizeBehavior)(nil), // 1: downsizer.DownsizeConfig.DownsizeBehavior
	(*durationpb.Duration)(nil),             // 2: google.protobuf.Duration
}
var file_pkg_ekvms_processor_proto_downsize_config_proto_depIdxs = []int32{
	1, // 0: downsizer.DownsizeConfig.behaviors:type_name -> downsizer.DownsizeConfig.DownsizeBehavior
	2, // 1: downsizer.DownsizeConfig.smoothing_window_length:type_name -> google.protobuf.Duration
	2, // 2: downsizer.DownsizeConfig.DownsizeBehavior.downsize_delay:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_ekvms_processor_proto_downsize_config_proto_init() }
func file_pkg_ekvms_processor_proto_downsize_config_proto_init() {
	if File_pkg_ekvms_processor_proto_downsize_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownsizeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownsizeConfig_DownsizeBehavior); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ekvms_processor_proto_downsize_config_proto_goTypes,
		DependencyIndexes: file_pkg_ekvms_processor_proto_downsize_config_proto_depIdxs,
		MessageInfos:      file_pkg_ekvms_processor_proto_downsize_config_proto_msgTypes,
	}.Build()
	File_pkg_ekvms_processor_proto_downsize_config_proto = out.File
	file_pkg_ekvms_processor_proto_downsize_config_proto_rawDesc = nil
	file_pkg_ekvms_processor_proto_downsize_config_proto_goTypes = nil
	file_pkg_ekvms_processor_proto_downsize_config_proto_depIdxs = nil
}
