// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/client/clientset/versioned"
	internalinterfaces "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/client/informers/externalversions/internalinterfaces"
	v1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/client/listers/cloud.google.com/v1"
	cloudgooglecomv1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/cloud.google.com/v1"
)

// MachineConfigInformer provides access to a shared informer and lister for
// MachineConfigs.
type MachineConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MachineConfigLister
}

type machineConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMachineConfigInformer constructs a new informer for MachineConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMachineConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMachineConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMachineConfigInformer constructs a new informer for MachineConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMachineConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().MachineConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().MachineConfigs().Watch(context.TODO(), options)
			},
		},
		&cloudgooglecomv1.MachineConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *machineConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMachineConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *machineConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cloudgooglecomv1.MachineConfig{}, f.defaultInformer)
}

func (f *machineConfigInformer) Lister() v1.MachineConfigLister {
	return v1.NewMachineConfigLister(f.Informer().GetIndexer())
}
