// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/cloud.google.com/v1"
)

// MachineConfigLister helps list MachineConfigs.
// All objects returned here must be treated as read-only.
type MachineConfigLister interface {
	// List lists all MachineConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.MachineConfig, err error)
	// Get retrieves the MachineConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.MachineConfig, error)
	MachineConfigListerExpansion
}

// machineConfigLister implements the MachineConfigLister interface.
type machineConfigLister struct {
	indexer cache.Indexer
}

// NewMachineConfigLister returns a new MachineConfigLister.
func NewMachineConfigLister(indexer cache.Indexer) MachineConfigLister {
	return &machineConfigLister{indexer: indexer}
}

// List lists all MachineConfigs in the indexer.
func (s *machineConfigLister) List(selector labels.Selector) (ret []*v1.MachineConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MachineConfig))
	})
	return ret, err
}

// Get retrieves the MachineConfig from the index for a given name.
func (s *machineConfigLister) Get(name string) (*v1.MachineConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("machineconfig"), name)
	}
	return obj.(*v1.MachineConfig), nil
}
