// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/apis/nodemanagement.gke.io/v1alpha1"
	scheme "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/client/clientset/versioned/scheme"
)

// UpdateInfosGetter has a method to return a UpdateInfoInterface.
// A group's client should implement this interface.
type UpdateInfosGetter interface {
	UpdateInfos(namespace string) UpdateInfoInterface
}

// UpdateInfoInterface has methods to work with UpdateInfo resources.
type UpdateInfoInterface interface {
	Create(ctx context.Context, updateInfo *v1alpha1.UpdateInfo, opts v1.CreateOptions) (*v1alpha1.UpdateInfo, error)
	Update(ctx context.Context, updateInfo *v1alpha1.UpdateInfo, opts v1.UpdateOptions) (*v1alpha1.UpdateInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.UpdateInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UpdateInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpdateInfo, err error)
	UpdateInfoExpansion
}

// updateInfos implements UpdateInfoInterface
type updateInfos struct {
	client rest.Interface
	ns     string
}

// newUpdateInfos returns a UpdateInfos
func newUpdateInfos(c *NodemanagementV1alpha1Client, namespace string) *updateInfos {
	return &updateInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the updateInfo, and returns the corresponding updateInfo object, and an error if there is any.
func (c *updateInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UpdateInfo, err error) {
	result = &v1alpha1.UpdateInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("updateinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UpdateInfos that match those selectors.
func (c *updateInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UpdateInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UpdateInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("updateinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested updateInfos.
func (c *updateInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("updateinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a updateInfo and creates it.  Returns the server's representation of the updateInfo, and an error, if there is any.
func (c *updateInfos) Create(ctx context.Context, updateInfo *v1alpha1.UpdateInfo, opts v1.CreateOptions) (result *v1alpha1.UpdateInfo, err error) {
	result = &v1alpha1.UpdateInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("updateinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(updateInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a updateInfo and updates it. Returns the server's representation of the updateInfo, and an error, if there is any.
func (c *updateInfos) Update(ctx context.Context, updateInfo *v1alpha1.UpdateInfo, opts v1.UpdateOptions) (result *v1alpha1.UpdateInfo, err error) {
	result = &v1alpha1.UpdateInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("updateinfos").
		Name(updateInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(updateInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the updateInfo and deletes it. Returns an error if one occurs.
func (c *updateInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("updateinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *updateInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("updateinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched updateInfo.
func (c *updateInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpdateInfo, err error) {
	result = &v1alpha1.UpdateInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("updateinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
