// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AcceleratorConfigApplyConfiguration represents an declarative configuration of the AcceleratorConfig type for use
// with apply.
type AcceleratorConfigApplyConfiguration struct {
	Count     *int64 `json:"count,omitempty"`
	MaxCPUs   *int64 `json:"maxCPUs,omitempty"`
	MaxMemory *int64 `json:"maxMemory,omitempty"`
}

// AcceleratorConfigApplyConfiguration constructs an declarative configuration of the AcceleratorConfig type for use with
// apply.
func AcceleratorConfig() *AcceleratorConfigApplyConfiguration {
	return &AcceleratorConfigApplyConfiguration{}
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *AcceleratorConfigApplyConfiguration) WithCount(value int64) *AcceleratorConfigApplyConfiguration {
	b.Count = &value
	return b
}

// WithMaxCPUs sets the MaxCPUs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCPUs field is set to the value of the last call.
func (b *AcceleratorConfigApplyConfiguration) WithMaxCPUs(value int64) *AcceleratorConfigApplyConfiguration {
	b.MaxCPUs = &value
	return b
}

// WithMaxMemory sets the MaxMemory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMemory field is set to the value of the last call.
func (b *AcceleratorConfigApplyConfiguration) WithMaxMemory(value int64) *AcceleratorConfigApplyConfiguration {
	b.MaxMemory = &value
	return b
}
