// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AcceleratorApplyConfiguration represents an declarative configuration of the Accelerator type for use
// with apply.
type AcceleratorApplyConfiguration struct {
	Name                          *string                               `json:"name,omitempty"`
	Configurations                []AcceleratorConfigApplyConfiguration `json:"configurations,omitempty"`
	PartitionSizes                map[string]int64                      `json:"partitionSizes,omitempty"`
	Weight                        *string                               `json:"weight,omitempty"`
	PreemptibleWeight             *string                               `json:"preemptibleWeight,omitempty"`
	ProviderType                  *string                               `json:"providerType,omitempty"`
	Topologies                    []string                              `json:"topologies,omitempty"`
	MultiInstanceSharingSupported *bool                                 `json:"multiInstanceSharingSupported,omitempty"`
	TimeSharingSupported          *bool                                 `json:"timeSharingSupported,omitempty"`
}

// AcceleratorApplyConfiguration constructs an declarative configuration of the Accelerator type for use with
// apply.
func Accelerator() *AcceleratorApplyConfiguration {
	return &AcceleratorApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AcceleratorApplyConfiguration) WithName(value string) *AcceleratorApplyConfiguration {
	b.Name = &value
	return b
}

// WithConfigurations adds the given value to the Configurations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Configurations field.
func (b *AcceleratorApplyConfiguration) WithConfigurations(values ...*AcceleratorConfigApplyConfiguration) *AcceleratorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConfigurations")
		}
		b.Configurations = append(b.Configurations, *values[i])
	}
	return b
}

// WithPartitionSizes puts the entries into the PartitionSizes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PartitionSizes field,
// overwriting an existing map entries in PartitionSizes field with the same key.
func (b *AcceleratorApplyConfiguration) WithPartitionSizes(entries map[string]int64) *AcceleratorApplyConfiguration {
	if b.PartitionSizes == nil && len(entries) > 0 {
		b.PartitionSizes = make(map[string]int64, len(entries))
	}
	for k, v := range entries {
		b.PartitionSizes[k] = v
	}
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *AcceleratorApplyConfiguration) WithWeight(value string) *AcceleratorApplyConfiguration {
	b.Weight = &value
	return b
}

// WithPreemptibleWeight sets the PreemptibleWeight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreemptibleWeight field is set to the value of the last call.
func (b *AcceleratorApplyConfiguration) WithPreemptibleWeight(value string) *AcceleratorApplyConfiguration {
	b.PreemptibleWeight = &value
	return b
}

// WithProviderType sets the ProviderType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderType field is set to the value of the last call.
func (b *AcceleratorApplyConfiguration) WithProviderType(value string) *AcceleratorApplyConfiguration {
	b.ProviderType = &value
	return b
}

// WithTopologies adds the given value to the Topologies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Topologies field.
func (b *AcceleratorApplyConfiguration) WithTopologies(values ...string) *AcceleratorApplyConfiguration {
	for i := range values {
		b.Topologies = append(b.Topologies, values[i])
	}
	return b
}

// WithMultiInstanceSharingSupported sets the MultiInstanceSharingSupported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MultiInstanceSharingSupported field is set to the value of the last call.
func (b *AcceleratorApplyConfiguration) WithMultiInstanceSharingSupported(value bool) *AcceleratorApplyConfiguration {
	b.MultiInstanceSharingSupported = &value
	return b
}

// WithTimeSharingSupported sets the TimeSharingSupported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeSharingSupported field is set to the value of the last call.
func (b *AcceleratorApplyConfiguration) WithTimeSharingSupported(value bool) *AcceleratorApplyConfiguration {
	b.TimeSharingSupported = &value
	return b
}
