// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BootDiskConfigApplyConfiguration represents an declarative configuration of the BootDiskConfig type for use
// with apply.
type BootDiskConfigApplyConfiguration struct {
	Types       []string `json:"types,omitempty"`
	DefaultType *string  `json:"defaultType,omitempty"`
}

// BootDiskConfigApplyConfiguration constructs an declarative configuration of the BootDiskConfig type for use with
// apply.
func BootDiskConfig() *BootDiskConfigApplyConfiguration {
	return &BootDiskConfigApplyConfiguration{}
}

// WithTypes adds the given value to the Types field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Types field.
func (b *BootDiskConfigApplyConfiguration) WithTypes(values ...string) *BootDiskConfigApplyConfiguration {
	for i := range values {
		b.Types = append(b.Types, values[i])
	}
	return b
}

// WithDefaultType sets the DefaultType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultType field is set to the value of the last call.
func (b *BootDiskConfigApplyConfiguration) WithDefaultType(value string) *BootDiskConfigApplyConfiguration {
	b.DefaultType = &value
	return b
}
