// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CompactPlacementConfigApplyConfiguration represents an declarative configuration of the CompactPlacementConfig type for use
// with apply.
type CompactPlacementConfigApplyConfiguration struct {
	Supported *bool  `json:"supported,omitempty"`
	MaxCount  *int64 `json:"maxCount,omitempty"`
}

// CompactPlacementConfigApplyConfiguration constructs an declarative configuration of the CompactPlacementConfig type for use with
// apply.
func CompactPlacementConfig() *CompactPlacementConfigApplyConfiguration {
	return &CompactPlacementConfigApplyConfiguration{}
}

// WithSupported sets the Supported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Supported field is set to the value of the last call.
func (b *CompactPlacementConfigApplyConfiguration) WithSupported(value bool) *CompactPlacementConfigApplyConfiguration {
	b.Supported = &value
	return b
}

// WithMaxCount sets the MaxCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCount field is set to the value of the last call.
func (b *CompactPlacementConfigApplyConfiguration) WithMaxCount(value int64) *CompactPlacementConfigApplyConfiguration {
	b.MaxCount = &value
	return b
}
