// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ConfidentialNodeConfigApplyConfiguration represents an declarative configuration of the ConfidentialNodeConfig type for use
// with apply.
type ConfidentialNodeConfigApplyConfiguration struct {
	Supported *bool                                    `json:"supported,omitempty"`
	Types     []ConfidentialNodeTypeApplyConfiguration `json:"types,omitempty"`
}

// ConfidentialNodeConfigApplyConfiguration constructs an declarative configuration of the ConfidentialNodeConfig type for use with
// apply.
func ConfidentialNodeConfig() *ConfidentialNodeConfigApplyConfiguration {
	return &ConfidentialNodeConfigApplyConfiguration{}
}

// WithSupported sets the Supported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Supported field is set to the value of the last call.
func (b *ConfidentialNodeConfigApplyConfiguration) WithSupported(value bool) *ConfidentialNodeConfigApplyConfiguration {
	b.Supported = &value
	return b
}

// WithTypes adds the given value to the Types field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Types field.
func (b *ConfidentialNodeConfigApplyConfiguration) WithTypes(values ...*ConfidentialNodeTypeApplyConfiguration) *ConfidentialNodeConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTypes")
		}
		b.Types = append(b.Types, *values[i])
	}
	return b
}
