// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MachineTypeWeightsApplyConfiguration represents an declarative configuration of the MachineTypeWeights type for use
// with apply.
type MachineTypeWeightsApplyConfiguration struct {
	InstanceWeight            *string `json:"instanceWeight,omitempty"`
	PreemptibleInstanceWeight *string `json:"preemptibleInstanceWeight,omitempty"`
}

// MachineTypeWeightsApplyConfiguration constructs an declarative configuration of the MachineTypeWeights type for use with
// apply.
func MachineTypeWeights() *MachineTypeWeightsApplyConfiguration {
	return &MachineTypeWeightsApplyConfiguration{}
}

// WithInstanceWeight sets the InstanceWeight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceWeight field is set to the value of the last call.
func (b *MachineTypeWeightsApplyConfiguration) WithInstanceWeight(value string) *MachineTypeWeightsApplyConfiguration {
	b.InstanceWeight = &value
	return b
}

// WithPreemptibleInstanceWeight sets the PreemptibleInstanceWeight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreemptibleInstanceWeight field is set to the value of the last call.
func (b *MachineTypeWeightsApplyConfiguration) WithPreemptibleInstanceWeight(value string) *MachineTypeWeightsApplyConfiguration {
	b.PreemptibleInstanceWeight = &value
	return b
}
