// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MachinePropertiesApplyConfiguration represents an declarative configuration of the MachineProperties type for use
// with apply.
type MachinePropertiesApplyConfiguration struct {
	SystemArchitecture        *string                                      `json:"systemArchitecture,omitempty"`
	CPUPlatforms              []CPUPlatformApplyConfiguration              `json:"cpuPlatforms,omitempty"`
	CompactPlacementConfig    *CompactPlacementConfigApplyConfiguration    `json:"compactPlacementConfig,omitempty"`
	ThreadsPerCore            *int64                                       `json:"threadsPerCore,omitempty"`
	BootDiskConfig            *BootDiskConfigApplyConfiguration            `json:"bootDiskConfig,omitempty"`
	PersistentDiskTypeConfigs []PersistentDiskTypeConfigApplyConfiguration `json:"persistentDiskTypeConfigs,omitempty"`
	NAPDisabled               *bool                                        `json:"napDisabled,omitempty"`
	SupportsConfidentialNodes *bool                                        `json:"supportsConfidentialNodes,omitempty"`
	ConfidentialNodeConfig    *ConfidentialNodeConfigApplyConfiguration    `json:"confidentialNodeConfig,omitempty"`
	NumaAlignmentUnsupported  *bool                                        `json:"numaAlignmentUnsupported,omitempty"`
}

// MachinePropertiesApplyConfiguration constructs an declarative configuration of the MachineProperties type for use with
// apply.
func MachineProperties() *MachinePropertiesApplyConfiguration {
	return &MachinePropertiesApplyConfiguration{}
}

// WithSystemArchitecture sets the SystemArchitecture field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemArchitecture field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithSystemArchitecture(value string) *MachinePropertiesApplyConfiguration {
	b.SystemArchitecture = &value
	return b
}

// WithCPUPlatforms adds the given value to the CPUPlatforms field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CPUPlatforms field.
func (b *MachinePropertiesApplyConfiguration) WithCPUPlatforms(values ...*CPUPlatformApplyConfiguration) *MachinePropertiesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCPUPlatforms")
		}
		b.CPUPlatforms = append(b.CPUPlatforms, *values[i])
	}
	return b
}

// WithCompactPlacementConfig sets the CompactPlacementConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompactPlacementConfig field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithCompactPlacementConfig(value *CompactPlacementConfigApplyConfiguration) *MachinePropertiesApplyConfiguration {
	b.CompactPlacementConfig = value
	return b
}

// WithThreadsPerCore sets the ThreadsPerCore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ThreadsPerCore field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithThreadsPerCore(value int64) *MachinePropertiesApplyConfiguration {
	b.ThreadsPerCore = &value
	return b
}

// WithBootDiskConfig sets the BootDiskConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootDiskConfig field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithBootDiskConfig(value *BootDiskConfigApplyConfiguration) *MachinePropertiesApplyConfiguration {
	b.BootDiskConfig = value
	return b
}

// WithPersistentDiskTypeConfigs adds the given value to the PersistentDiskTypeConfigs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PersistentDiskTypeConfigs field.
func (b *MachinePropertiesApplyConfiguration) WithPersistentDiskTypeConfigs(values ...*PersistentDiskTypeConfigApplyConfiguration) *MachinePropertiesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPersistentDiskTypeConfigs")
		}
		b.PersistentDiskTypeConfigs = append(b.PersistentDiskTypeConfigs, *values[i])
	}
	return b
}

// WithNAPDisabled sets the NAPDisabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NAPDisabled field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithNAPDisabled(value bool) *MachinePropertiesApplyConfiguration {
	b.NAPDisabled = &value
	return b
}

// WithSupportsConfidentialNodes sets the SupportsConfidentialNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SupportsConfidentialNodes field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithSupportsConfidentialNodes(value bool) *MachinePropertiesApplyConfiguration {
	b.SupportsConfidentialNodes = &value
	return b
}

// WithConfidentialNodeConfig sets the ConfidentialNodeConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfidentialNodeConfig field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithConfidentialNodeConfig(value *ConfidentialNodeConfigApplyConfiguration) *MachinePropertiesApplyConfiguration {
	b.ConfidentialNodeConfig = value
	return b
}

// WithNumaAlignmentUnsupported sets the NumaAlignmentUnsupported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumaAlignmentUnsupported field is set to the value of the last call.
func (b *MachinePropertiesApplyConfiguration) WithNumaAlignmentUnsupported(value bool) *MachinePropertiesApplyConfiguration {
	b.NumaAlignmentUnsupported = &value
	return b
}
