// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MachineTypeApplyConfiguration represents an declarative configuration of the MachineType type for use
// with apply.
type MachineTypeApplyConfiguration struct {
	Name       *string                               `json:"name,omitempty"`
	Resources  *MachineResourcesApplyConfiguration   `json:"resources,omitempty"`
	Weights    *MachineTypeWeightsApplyConfiguration `json:"weights,omitempty"`
	Properties *MachinePropertiesApplyConfiguration  `json:"properties,omitempty"`
}

// MachineTypeApplyConfiguration constructs an declarative configuration of the MachineType type for use with
// apply.
func MachineType() *MachineTypeApplyConfiguration {
	return &MachineTypeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MachineTypeApplyConfiguration) WithName(value string) *MachineTypeApplyConfiguration {
	b.Name = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *MachineTypeApplyConfiguration) WithResources(value *MachineResourcesApplyConfiguration) *MachineTypeApplyConfiguration {
	b.Resources = value
	return b
}

// WithWeights sets the Weights field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weights field is set to the value of the last call.
func (b *MachineTypeApplyConfiguration) WithWeights(value *MachineTypeWeightsApplyConfiguration) *MachineTypeApplyConfiguration {
	b.Weights = value
	return b
}

// WithProperties sets the Properties field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Properties field is set to the value of the last call.
func (b *MachineTypeApplyConfiguration) WithProperties(value *MachinePropertiesApplyConfiguration) *MachineTypeApplyConfiguration {
	b.Properties = value
	return b
}
