// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MachineFamilyApplyConfiguration represents an declarative configuration of the MachineFamily type for use
// with apply.
type MachineFamilyApplyConfiguration struct {
	Name              *string                                 `json:"name,omitempty"`
	UsagePolicy       *UsagePolicyApplyConfiguration          `json:"usagePolicy,omitempty"`
	DefaultProperties *MachinePropertiesApplyConfiguration    `json:"defaultProperties,omitempty"`
	Weights           *MachineFamilyWeightsApplyConfiguration `json:"weights,omitempty"`
	MachineTypes      []MachineTypeApplyConfiguration         `json:"machineTypes,omitempty"`
	Accelerators      []AcceleratorApplyConfiguration         `json:"accelerators,omitempty"`
	ComputeClasses    []string                                `json:"computeClasses,omitempty"`
	PageType          *string                                 `json:"pageType,omitempty"`
}

// MachineFamilyApplyConfiguration constructs an declarative configuration of the MachineFamily type for use with
// apply.
func MachineFamily() *MachineFamilyApplyConfiguration {
	return &MachineFamilyApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MachineFamilyApplyConfiguration) WithName(value string) *MachineFamilyApplyConfiguration {
	b.Name = &value
	return b
}

// WithUsagePolicy sets the UsagePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsagePolicy field is set to the value of the last call.
func (b *MachineFamilyApplyConfiguration) WithUsagePolicy(value *UsagePolicyApplyConfiguration) *MachineFamilyApplyConfiguration {
	b.UsagePolicy = value
	return b
}

// WithDefaultProperties sets the DefaultProperties field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultProperties field is set to the value of the last call.
func (b *MachineFamilyApplyConfiguration) WithDefaultProperties(value *MachinePropertiesApplyConfiguration) *MachineFamilyApplyConfiguration {
	b.DefaultProperties = value
	return b
}

// WithWeights sets the Weights field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weights field is set to the value of the last call.
func (b *MachineFamilyApplyConfiguration) WithWeights(value *MachineFamilyWeightsApplyConfiguration) *MachineFamilyApplyConfiguration {
	b.Weights = value
	return b
}

// WithMachineTypes adds the given value to the MachineTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MachineTypes field.
func (b *MachineFamilyApplyConfiguration) WithMachineTypes(values ...*MachineTypeApplyConfiguration) *MachineFamilyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMachineTypes")
		}
		b.MachineTypes = append(b.MachineTypes, *values[i])
	}
	return b
}

// WithAccelerators adds the given value to the Accelerators field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Accelerators field.
func (b *MachineFamilyApplyConfiguration) WithAccelerators(values ...*AcceleratorApplyConfiguration) *MachineFamilyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccelerators")
		}
		b.Accelerators = append(b.Accelerators, *values[i])
	}
	return b
}

// WithComputeClasses adds the given value to the ComputeClasses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ComputeClasses field.
func (b *MachineFamilyApplyConfiguration) WithComputeClasses(values ...string) *MachineFamilyApplyConfiguration {
	for i := range values {
		b.ComputeClasses = append(b.ComputeClasses, values[i])
	}
	return b
}

// WithPageType sets the PageType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PageType field is set to the value of the last call.
func (b *MachineFamilyApplyConfiguration) WithPageType(value string) *MachineFamilyApplyConfiguration {
	b.PageType = &value
	return b
}
