// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/provisioningrequests/apis/provisioning.x-k8s.io/v1alpha1"
	provisioningxk8siov1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/provisioningrequests/client/applyconfiguration/provisioning.x-k8s.io/v1alpha1"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=provisioning.x-k8s.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("PodSet"):
		return &provisioningxk8siov1alpha1.PodSetApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProvisioningRequest"):
		return &provisioningxk8siov1alpha1.ProvisioningRequestApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProvisioningRequestSpec"):
		return &provisioningxk8siov1alpha1.ProvisioningRequestSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProvisioningRequestStatus"):
		return &provisioningxk8siov1alpha1.ProvisioningRequestStatusApplyConfiguration{}

	}
	return nil
}
