// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file shouldn't be modified directly. Its source of truth is located
// in the GKE UI codebase:
// cs//depot/google3/java/com/google/cloud/boq/clientapi/resource/container/proto/clusterautoscalervisibility.proto
// If you want to change anything, first submit the changes there and get the
// UI team approval, then sync this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: pkg/visibility/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message to differentiate between the types of events. This will appear in
// Stackdriver Logging log entries in the json_payload field, defined here:
// http://cs//depot/google3/google/logging/v2/log_entry.proto.
type AutoscalerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EventOneof:
	//
	//	*AutoscalerEvent_Status
	//	*AutoscalerEvent_Decision
	//	*AutoscalerEvent_ResultInfo
	//	*AutoscalerEvent_NoDecisionStatus
	EventOneof    isAutoscalerEvent_EventOneof `protobuf_oneof:"event_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoscalerEvent) Reset() {
	*x = AutoscalerEvent{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalerEvent) ProtoMessage() {}

func (x *AutoscalerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalerEvent.ProtoReflect.Descriptor instead.
func (*AutoscalerEvent) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *AutoscalerEvent) GetEventOneof() isAutoscalerEvent_EventOneof {
	if x != nil {
		return x.EventOneof
	}
	return nil
}

func (x *AutoscalerEvent) GetStatus() *ClusterStatus {
	if x != nil {
		if x, ok := x.EventOneof.(*AutoscalerEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AutoscalerEvent) GetDecision() *DecisionEvent {
	if x != nil {
		if x, ok := x.EventOneof.(*AutoscalerEvent_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *AutoscalerEvent) GetResultInfo() *ResultInfo {
	if x != nil {
		if x, ok := x.EventOneof.(*AutoscalerEvent_ResultInfo); ok {
			return x.ResultInfo
		}
	}
	return nil
}

func (x *AutoscalerEvent) GetNoDecisionStatus() *NoDecisionStatus {
	if x != nil {
		if x, ok := x.EventOneof.(*AutoscalerEvent_NoDecisionStatus); ok {
			return x.NoDecisionStatus
		}
	}
	return nil
}

type isAutoscalerEvent_EventOneof interface {
	isAutoscalerEvent_EventOneof()
}

type AutoscalerEvent_Status struct {
	Status *ClusterStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type AutoscalerEvent_Decision struct {
	Decision *DecisionEvent `protobuf:"bytes,2,opt,name=decision,proto3,oneof"`
}

type AutoscalerEvent_ResultInfo struct {
	ResultInfo *ResultInfo `protobuf:"bytes,3,opt,name=result_info,json=resultInfo,proto3,oneof"`
}

type AutoscalerEvent_NoDecisionStatus struct {
	NoDecisionStatus *NoDecisionStatus `protobuf:"bytes,4,opt,name=no_decision_status,json=noDecisionStatus,proto3,oneof"`
}

func (*AutoscalerEvent_Status) isAutoscalerEvent_EventOneof() {}

func (*AutoscalerEvent_Decision) isAutoscalerEvent_EventOneof() {}

func (*AutoscalerEvent_ResultInfo) isAutoscalerEvent_EventOneof() {}

func (*AutoscalerEvent_NoDecisionStatus) isAutoscalerEvent_EventOneof() {}

// A high-level description of Cluster status
// generated periodically regardless of any Cluster Autoscaler decisions.
type ClusterStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	MeasureTime int64 `protobuf:"varint,1,opt,name=measure_time,json=measureTime,proto3" json:"measure_time,omitempty"`
	// Required. The sum of the number of nodes in all autoscaled node pools.
	AutoscaledNodesCount int32 `protobuf:"varint,2,opt,name=autoscaled_nodes_count,json=autoscaledNodesCount,proto3" json:"autoscaled_nodes_count,omitempty"`
	// Required. The target amount of nodes in all autoscaled node pools.
	AutoscaledNodesTarget int32 `protobuf:"varint,3,opt,name=autoscaled_nodes_target,json=autoscaledNodesTarget,proto3" json:"autoscaled_nodes_target,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterStatus) GetMeasureTime() int64 {
	if x != nil {
		return x.MeasureTime
	}
	return 0
}

func (x *ClusterStatus) GetAutoscaledNodesCount() int32 {
	if x != nil {
		return x.AutoscaledNodesCount
	}
	return 0
}

func (x *ClusterStatus) GetAutoscaledNodesTarget() int32 {
	if x != nil {
		return x.AutoscaledNodesTarget
	}
	return 0
}

// A message containing the results of finished events.
type ResultInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	MeasureTime   int64          `protobuf:"varint,1,opt,name=measure_time,json=measureTime,proto3" json:"measure_time,omitempty"`
	Results       []*EventResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultInfo) Reset() {
	*x = ResultInfo{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultInfo) ProtoMessage() {}

func (x *ResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultInfo.ProtoReflect.Descriptor instead.
func (*ResultInfo) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *ResultInfo) GetMeasureTime() int64 {
	if x != nil {
		return x.MeasureTime
	}
	return 0
}

func (x *ResultInfo) GetResults() []*EventResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// A structure describing a finished event, indicating if the event finished
// successfully: if it did not, there is an error message present.
type EventResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Optional.
	ErrorMsg      *ParametrizedMessage `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResult) Reset() {
	*x = EventResult{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResult) ProtoMessage() {}

func (x *EventResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResult.ProtoReflect.Descriptor instead.
func (*EventResult) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventResult) GetErrorMsg() *ParametrizedMessage {
	if x != nil {
		return x.ErrorMsg
	}
	return nil
}

// An event for a single decision.
type DecisionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Unix timestamp.
	DecideTime int64 `protobuf:"varint,1,opt,name=decide_time,json=decideTime,proto3" json:"decide_time,omitempty"`
	// Required. Unique inside a single cluster.
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are valid to be assigned to DecisionOneof:
	//
	//	*DecisionEvent_ScaleUp
	//	*DecisionEvent_ScaleDown
	//	*DecisionEvent_NodePoolCreated
	//	*DecisionEvent_NodePoolDeleted
	DecisionOneof isDecisionEvent_DecisionOneof `protobuf_oneof:"decision_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionEvent) Reset() {
	*x = DecisionEvent{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionEvent) ProtoMessage() {}

func (x *DecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionEvent.ProtoReflect.Descriptor instead.
func (*DecisionEvent) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionEvent) GetDecideTime() int64 {
	if x != nil {
		return x.DecideTime
	}
	return 0
}

func (x *DecisionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DecisionEvent) GetDecisionOneof() isDecisionEvent_DecisionOneof {
	if x != nil {
		return x.DecisionOneof
	}
	return nil
}

func (x *DecisionEvent) GetScaleUp() *ScaleUpData {
	if x != nil {
		if x, ok := x.DecisionOneof.(*DecisionEvent_ScaleUp); ok {
			return x.ScaleUp
		}
	}
	return nil
}

func (x *DecisionEvent) GetScaleDown() *ScaleDownData {
	if x != nil {
		if x, ok := x.DecisionOneof.(*DecisionEvent_ScaleDown); ok {
			return x.ScaleDown
		}
	}
	return nil
}

func (x *DecisionEvent) GetNodePoolCreated() *NodePoolCreatedData {
	if x != nil {
		if x, ok := x.DecisionOneof.(*DecisionEvent_NodePoolCreated); ok {
			return x.NodePoolCreated
		}
	}
	return nil
}

func (x *DecisionEvent) GetNodePoolDeleted() *NodePoolDeletedData {
	if x != nil {
		if x, ok := x.DecisionOneof.(*DecisionEvent_NodePoolDeleted); ok {
			return x.NodePoolDeleted
		}
	}
	return nil
}

type isDecisionEvent_DecisionOneof interface {
	isDecisionEvent_DecisionOneof()
}

type DecisionEvent_ScaleUp struct {
	ScaleUp *ScaleUpData `protobuf:"bytes,10,opt,name=scale_up,json=scaleUp,proto3,oneof"`
}

type DecisionEvent_ScaleDown struct {
	ScaleDown *ScaleDownData `protobuf:"bytes,11,opt,name=scale_down,json=scaleDown,proto3,oneof"`
}

type DecisionEvent_NodePoolCreated struct {
	NodePoolCreated *NodePoolCreatedData `protobuf:"bytes,12,opt,name=node_pool_created,json=nodePoolCreated,proto3,oneof"`
}

type DecisionEvent_NodePoolDeleted struct {
	NodePoolDeleted *NodePoolDeletedData `protobuf:"bytes,13,opt,name=node_pool_deleted,json=nodePoolDeleted,proto3,oneof"`
}

func (*DecisionEvent_ScaleUp) isDecisionEvent_DecisionOneof() {}

func (*DecisionEvent_ScaleDown) isDecisionEvent_DecisionOneof() {}

func (*DecisionEvent_NodePoolCreated) isDecisionEvent_DecisionOneof() {}

func (*DecisionEvent_NodePoolDeleted) isDecisionEvent_DecisionOneof() {}

type NoDecisionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	MeasureTime int64 `protobuf:"varint,1,opt,name=measure_time,json=measureTime,proto3" json:"measure_time,omitempty"`
	// Types that are valid to be assigned to KindOneof:
	//
	//	*NoDecisionStatus_NoScaleUp
	//	*NoDecisionStatus_NoScaleDown
	KindOneof     isNoDecisionStatus_KindOneof `protobuf_oneof:"kind_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoDecisionStatus) Reset() {
	*x = NoDecisionStatus{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoDecisionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoDecisionStatus) ProtoMessage() {}

func (x *NoDecisionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoDecisionStatus.ProtoReflect.Descriptor instead.
func (*NoDecisionStatus) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *NoDecisionStatus) GetMeasureTime() int64 {
	if x != nil {
		return x.MeasureTime
	}
	return 0
}

func (x *NoDecisionStatus) GetKindOneof() isNoDecisionStatus_KindOneof {
	if x != nil {
		return x.KindOneof
	}
	return nil
}

func (x *NoDecisionStatus) GetNoScaleUp() *NoScaleUpData {
	if x != nil {
		if x, ok := x.KindOneof.(*NoDecisionStatus_NoScaleUp); ok {
			return x.NoScaleUp
		}
	}
	return nil
}

func (x *NoDecisionStatus) GetNoScaleDown() *NoScaleDownData {
	if x != nil {
		if x, ok := x.KindOneof.(*NoDecisionStatus_NoScaleDown); ok {
			return x.NoScaleDown
		}
	}
	return nil
}

type isNoDecisionStatus_KindOneof interface {
	isNoDecisionStatus_KindOneof()
}

type NoDecisionStatus_NoScaleUp struct {
	NoScaleUp *NoScaleUpData `protobuf:"bytes,10,opt,name=no_scale_up,json=noScaleUp,proto3,oneof"`
}

type NoDecisionStatus_NoScaleDown struct {
	NoScaleDown *NoScaleDownData `protobuf:"bytes,11,opt,name=no_scale_down,json=noScaleDown,proto3,oneof"`
}

func (*NoDecisionStatus_NoScaleUp) isNoDecisionStatus_KindOneof() {}

func (*NoDecisionStatus_NoScaleDown) isNoDecisionStatus_KindOneof() {}

// Data specific to a scale-up event.
type ScaleUpData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The decision / requested increase.
	IncreasedMigs []*ScaleUpMig `protobuf:"bytes,1,rep,name=increased_migs,json=increasedMigs,proto3" json:"increased_migs,omitempty"`
	// List of pods triggering scale-up. This list can be truncated.
	TriggeringPods []*Pod `protobuf:"bytes,10,rep,name=triggering_pods,json=triggeringPods,proto3" json:"triggering_pods,omitempty"`
	// Total number of triggering pods, regardless of truncation.
	// Required.
	TriggeringPodsTotalCount int32 `protobuf:"varint,11,opt,name=triggering_pods_total_count,json=triggeringPodsTotalCount,proto3" json:"triggering_pods_total_count,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ScaleUpData) Reset() {
	*x = ScaleUpData{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleUpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleUpData) ProtoMessage() {}

func (x *ScaleUpData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleUpData.ProtoReflect.Descriptor instead.
func (*ScaleUpData) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *ScaleUpData) GetIncreasedMigs() []*ScaleUpMig {
	if x != nil {
		return x.IncreasedMigs
	}
	return nil
}

func (x *ScaleUpData) GetTriggeringPods() []*Pod {
	if x != nil {
		return x.TriggeringPods
	}
	return nil
}

func (x *ScaleUpData) GetTriggeringPodsTotalCount() int32 {
	if x != nil {
		return x.TriggeringPodsTotalCount
	}
	return 0
}

// Data specific to a scale-down event.
type ScaleDownData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The decision / requested decrease.
	NodesToBeRemoved []*ScaleDownNode `protobuf:"bytes,1,rep,name=nodes_to_be_removed,json=nodesToBeRemoved,proto3" json:"nodes_to_be_removed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScaleDownData) Reset() {
	*x = ScaleDownData{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleDownData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleDownData) ProtoMessage() {}

func (x *ScaleDownData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleDownData.ProtoReflect.Descriptor instead.
func (*ScaleDownData) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *ScaleDownData) GetNodesToBeRemoved() []*ScaleDownNode {
	if x != nil {
		return x.NodesToBeRemoved
	}
	return nil
}

// Data specific to a no-scale-up decision.
type NoScaleUpData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Top-level reason for no scale-up (e.g. no.pending.pods,
	// state.unhealthy or nodes.too.fresh.to.act).
	// Optional.
	Reason *ParametrizedMessage `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// Top-level reason why no node pools were autoprovisioned.
	// Optional.
	NapFailureReason *ParametrizedMessage `protobuf:"bytes,2,opt,name=nap_failure_reason,json=napFailureReason,proto3" json:"nap_failure_reason,omitempty"`
	// A list of pod groups that didn’t trigger a scale-up, with explanations why.
	// This list can be truncated.
	UnhandledPodGroups []*PodGroupExplanation `protobuf:"bytes,3,rep,name=unhandled_pod_groups,json=unhandledPodGroups,proto3" json:"unhandled_pod_groups,omitempty"`
	// Total number of unhandled pod groups, regardless of truncation.
	// Required.
	UnhandledPodGroupsTotalCount int32 `protobuf:"varint,4,opt,name=unhandled_pod_groups_total_count,json=unhandledPodGroupsTotalCount,proto3" json:"unhandled_pod_groups_total_count,omitempty"`
	// List of skipped MIGs, with reasons why.
	SkippedMigs   []*MigExplanation `protobuf:"bytes,5,rep,name=skipped_migs,json=skippedMigs,proto3" json:"skipped_migs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoScaleUpData) Reset() {
	*x = NoScaleUpData{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoScaleUpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoScaleUpData) ProtoMessage() {}

func (x *NoScaleUpData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoScaleUpData.ProtoReflect.Descriptor instead.
func (*NoScaleUpData) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *NoScaleUpData) GetReason() *ParametrizedMessage {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *NoScaleUpData) GetNapFailureReason() *ParametrizedMessage {
	if x != nil {
		return x.NapFailureReason
	}
	return nil
}

func (x *NoScaleUpData) GetUnhandledPodGroups() []*PodGroupExplanation {
	if x != nil {
		return x.UnhandledPodGroups
	}
	return nil
}

func (x *NoScaleUpData) GetUnhandledPodGroupsTotalCount() int32 {
	if x != nil {
		return x.UnhandledPodGroupsTotalCount
	}
	return 0
}

func (x *NoScaleUpData) GetSkippedMigs() []*MigExplanation {
	if x != nil {
		return x.SkippedMigs
	}
	return nil
}

// Data specific to a no-scale-down decision.
type NoScaleDownData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Top-level reason for no scale-down (e.g. no.candidates
	// or scaleup.early.exit).
	// Optional.
	Reason *ParametrizedMessage `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// List of underutilized nodes which were not scaled down,
	// with per-node explanations. This list can be truncated.
	Nodes []*NodeExplanation `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Total number of underutilized nodes, regardless of truncation.
	// Required.
	NodesTotalCount int32 `protobuf:"varint,4,opt,name=nodes_total_count,json=nodesTotalCount,proto3" json:"nodes_total_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NoScaleDownData) Reset() {
	*x = NoScaleDownData{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoScaleDownData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoScaleDownData) ProtoMessage() {}

func (x *NoScaleDownData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoScaleDownData.ProtoReflect.Descriptor instead.
func (*NoScaleDownData) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *NoScaleDownData) GetReason() *ParametrizedMessage {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *NoScaleDownData) GetNodes() []*NodeExplanation {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NoScaleDownData) GetNodesTotalCount() int32 {
	if x != nil {
		return x.NodesTotalCount
	}
	return 0
}

type NodePoolCreatedData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodePools []*NodePool            `protobuf:"bytes,1,rep,name=node_pools,json=nodePools,proto3" json:"node_pools,omitempty"`
	// If the node pool(s) were created because of a scale-up, the scale-up event
	// id should be put here.
	// Optional.
	TriggeringScaleUpId string `protobuf:"bytes,2,opt,name=triggering_scale_up_id,json=triggeringScaleUpId,proto3" json:"triggering_scale_up_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodePoolCreatedData) Reset() {
	*x = NodePoolCreatedData{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePoolCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePoolCreatedData) ProtoMessage() {}

func (x *NodePoolCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePoolCreatedData.ProtoReflect.Descriptor instead.
func (*NodePoolCreatedData) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *NodePoolCreatedData) GetNodePools() []*NodePool {
	if x != nil {
		return x.NodePools
	}
	return nil
}

func (x *NodePoolCreatedData) GetTriggeringScaleUpId() string {
	if x != nil {
		return x.TriggeringScaleUpId
	}
	return ""
}

type NodePoolDeletedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodePoolNames []string               `protobuf:"bytes,1,rep,name=node_pool_names,json=nodePoolNames,proto3" json:"node_pool_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePoolDeletedData) Reset() {
	*x = NodePoolDeletedData{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePoolDeletedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePoolDeletedData) ProtoMessage() {}

func (x *NodePoolDeletedData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePoolDeletedData.ProtoReflect.Descriptor instead.
func (*NodePoolDeletedData) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *NodePoolDeletedData) GetNodePoolNames() []string {
	if x != nil {
		return x.NodePoolNames
	}
	return nil
}

// Scale-up data for a single MIG.
type ScaleUpMig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Mig *Mig `protobuf:"bytes,1,opt,name=mig,proto3" json:"mig,omitempty"`
	// Required. Number of new nodes requested.
	RequestedNodes int32 `protobuf:"varint,2,opt,name=requested_nodes,json=requestedNodes,proto3" json:"requested_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScaleUpMig) Reset() {
	*x = ScaleUpMig{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleUpMig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleUpMig) ProtoMessage() {}

func (x *ScaleUpMig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleUpMig.ProtoReflect.Descriptor instead.
func (*ScaleUpMig) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *ScaleUpMig) GetMig() *Mig {
	if x != nil {
		return x.Mig
	}
	return nil
}

func (x *ScaleUpMig) GetRequestedNodes() int32 {
	if x != nil {
		return x.RequestedNodes
	}
	return 0
}

// Data about the status of a MIG.
type MigStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Mig *Mig `protobuf:"bytes,1,opt,name=mig,proto3" json:"mig,omitempty"`
	// Required. The actual number of nodes in the MIG.
	ActualSize int32 `protobuf:"varint,2,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
	// Required. The target number of nodes in the MIG.
	TargetSize int32 `protobuf:"varint,3,opt,name=target_size,json=targetSize,proto3" json:"target_size,omitempty"`
	// Required. The min number of nodes in the MIG.
	MinSize int32 `protobuf:"varint,4,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	// Required. The max number of nodes in the MIG.
	MaxSize       int32 `protobuf:"varint,5,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigStatus) Reset() {
	*x = MigStatus{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigStatus) ProtoMessage() {}

func (x *MigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigStatus.ProtoReflect.Descriptor instead.
func (*MigStatus) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *MigStatus) GetMig() *Mig {
	if x != nil {
		return x.Mig
	}
	return nil
}

func (x *MigStatus) GetActualSize() int32 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

func (x *MigStatus) GetTargetSize() int32 {
	if x != nil {
		return x.TargetSize
	}
	return 0
}

func (x *MigStatus) GetMinSize() int32 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *MigStatus) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

// Scaled-down Node with a list of Pods that needed to be evicted.
type ScaleDownNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Evicted pods which are expected to move somewhere else (or rather
	// their replicas are). This list can be truncated.
	EvictedPods []*Pod `protobuf:"bytes,2,rep,name=evicted_pods,json=evictedPods,proto3" json:"evicted_pods,omitempty"`
	// Total number of evicted pods, regardless of truncation.
	// Required.
	EvictedPodsTotalCount int32 `protobuf:"varint,4,opt,name=evicted_pods_total_count,json=evictedPodsTotalCount,proto3" json:"evicted_pods_total_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ScaleDownNode) Reset() {
	*x = ScaleDownNode{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleDownNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleDownNode) ProtoMessage() {}

func (x *ScaleDownNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleDownNode.ProtoReflect.Descriptor instead.
func (*ScaleDownNode) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *ScaleDownNode) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ScaleDownNode) GetEvictedPods() []*Pod {
	if x != nil {
		return x.EvictedPods
	}
	return nil
}

func (x *ScaleDownNode) GetEvictedPodsTotalCount() int32 {
	if x != nil {
		return x.EvictedPodsTotalCount
	}
	return 0
}

type PodGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A sample pod from this group.
	SamplePod *Pod `protobuf:"bytes,1,opt,name=sample_pod,json=samplePod,proto3" json:"sample_pod,omitempty"`
	// Required. The total number of pods in this group.
	TotalPodCount int32 `protobuf:"varint,2,opt,name=total_pod_count,json=totalPodCount,proto3" json:"total_pod_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodGroup) Reset() {
	*x = PodGroup{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodGroup) ProtoMessage() {}

func (x *PodGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodGroup.ProtoReflect.Descriptor instead.
func (*PodGroup) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *PodGroup) GetSamplePod() *Pod {
	if x != nil {
		return x.SamplePod
	}
	return nil
}

func (x *PodGroup) GetTotalPodCount() int32 {
	if x != nil {
		return x.TotalPodCount
	}
	return 0
}

// Group of pods with a reason explaining a decision made for it.
type PodGroupExplanation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	PodGroup *PodGroup `protobuf:"bytes,1,opt,name=pod_group,json=podGroup,proto3" json:"pod_group,omitempty"`
	// List of MIGs rejected because of failing predicates, with reasons why.
	RejectedMigs []*MigExplanation `protobuf:"bytes,2,rep,name=rejected_migs,json=rejectedMigs,proto3" json:"rejected_migs,omitempty"`
	// Reasons why the pod didn't trigger new node pool creation.
	NapFailureReasons []*ParametrizedMessage `protobuf:"bytes,3,rep,name=nap_failure_reasons,json=napFailureReasons,proto3" json:"nap_failure_reasons,omitempty"`
	// List of MIGs skipped for this pod group, with reasons why.
	SkippedMigs   []*MigExplanation `protobuf:"bytes,4,rep,name=skipped_migs,json=skippedMigs,proto3" json:"skipped_migs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodGroupExplanation) Reset() {
	*x = PodGroupExplanation{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodGroupExplanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodGroupExplanation) ProtoMessage() {}

func (x *PodGroupExplanation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodGroupExplanation.ProtoReflect.Descriptor instead.
func (*PodGroupExplanation) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{16}
}

func (x *PodGroupExplanation) GetPodGroup() *PodGroup {
	if x != nil {
		return x.PodGroup
	}
	return nil
}

func (x *PodGroupExplanation) GetRejectedMigs() []*MigExplanation {
	if x != nil {
		return x.RejectedMigs
	}
	return nil
}

func (x *PodGroupExplanation) GetNapFailureReasons() []*ParametrizedMessage {
	if x != nil {
		return x.NapFailureReasons
	}
	return nil
}

func (x *PodGroupExplanation) GetSkippedMigs() []*MigExplanation {
	if x != nil {
		return x.SkippedMigs
	}
	return nil
}

// Node with a reason explaining a decision made for it.
type NodeExplanation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Required.
	Reason        *ParametrizedMessage `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeExplanation) Reset() {
	*x = NodeExplanation{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeExplanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExplanation) ProtoMessage() {}

func (x *NodeExplanation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExplanation.ProtoReflect.Descriptor instead.
func (*NodeExplanation) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{17}
}

func (x *NodeExplanation) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeExplanation) GetReason() *ParametrizedMessage {
	if x != nil {
		return x.Reason
	}
	return nil
}

// MIG with a reason explaining a decision made for it.
type MigExplanation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Mig *Mig `protobuf:"bytes,1,opt,name=mig,proto3" json:"mig,omitempty"`
	// Required.
	Reason        *ParametrizedMessage `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigExplanation) Reset() {
	*x = MigExplanation{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigExplanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigExplanation) ProtoMessage() {}

func (x *MigExplanation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigExplanation.ProtoReflect.Descriptor instead.
func (*MigExplanation) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{18}
}

func (x *MigExplanation) GetMig() *Mig {
	if x != nil {
		return x.Mig
	}
	return nil
}

func (x *MigExplanation) GetReason() *ParametrizedMessage {
	if x != nil {
		return x.Reason
	}
	return nil
}

// Data required to render a message for the end-user, allowing for i18n.
// Assuming a very naive i18n for a text like "Added 10 nodes" this proto
// would contain:
// message_id = nodes.added
// parameters[0] = 10
// and the English text would be configured as nodes.added=Added {0} nodes.
// The messages are defined here: go/ca-viz-api-msgs.
type ParametrizedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Property key describing the message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Additional data to fill in the placeholders, if any.
	Parameters    []string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParametrizedMessage) Reset() {
	*x = ParametrizedMessage{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParametrizedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametrizedMessage) ProtoMessage() {}

func (x *ParametrizedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametrizedMessage.ProtoReflect.Descriptor instead.
func (*ParametrizedMessage) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{19}
}

func (x *ParametrizedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ParametrizedMessage) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Represents a Managed Instance Group.
type Mig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Name of the MIG.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. Name of the nodepool the MIG belongs to.
	Nodepool string `protobuf:"bytes,2,opt,name=nodepool,proto3" json:"nodepool,omitempty"`
	// Required. Name of the zone the MIG is in.
	Zone          string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mig) Reset() {
	*x = Mig{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mig) ProtoMessage() {}

func (x *Mig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mig.ProtoReflect.Descriptor instead.
func (*Mig) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{20}
}

func (x *Mig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mig) GetNodepool() string {
	if x != nil {
		return x.Nodepool
	}
	return ""
}

func (x *Mig) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

// Represents a GKE node pool.
type NodePool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Migs          []*Mig `protobuf:"bytes,2,rep,name=migs,proto3" json:"migs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePool) Reset() {
	*x = NodePool{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePool) ProtoMessage() {}

func (x *NodePool) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePool.ProtoReflect.Descriptor instead.
func (*NodePool) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{21}
}

func (x *NodePool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodePool) GetMigs() []*Mig {
	if x != nil {
		return x.Migs
	}
	return nil
}

// Node, from Kubernetes API.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required.
	Mig *Mig `protobuf:"bytes,2,opt,name=mig,proto3" json:"mig,omitempty"`
	// Optional. Ratio requested/allocatable CPU, in %.
	CpuRatio int32 `protobuf:"varint,3,opt,name=cpu_ratio,json=cpuRatio,proto3" json:"cpu_ratio,omitempty"`
	// Optional. Ratio requested/allocatable memory, in %.
	MemRatio      int32 `protobuf:"varint,4,opt,name=mem_ratio,json=memRatio,proto3" json:"mem_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{22}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetMig() *Mig {
	if x != nil {
		return x.Mig
	}
	return nil
}

func (x *Node) GetCpuRatio() int32 {
	if x != nil {
		return x.CpuRatio
	}
	return 0
}

func (x *Node) GetMemRatio() int32 {
	if x != nil {
		return x.MemRatio
	}
	return 0
}

// Pod, from Kubernetes API.
type Pod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional.
	Controller *PodController `protobuf:"bytes,2,opt,name=controller,proto3" json:"controller,omitempty"`
	// Required.
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{23}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetController() *PodController {
	if x != nil {
		return x.Controller
	}
	return nil
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Pod Controller, from Kubernetes API.
type PodController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Required.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Required.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodController) Reset() {
	*x = PodController{}
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodController) ProtoMessage() {}

func (x *PodController) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_visibility_proto_events_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodController.ProtoReflect.Descriptor instead.
func (*PodController) Descriptor() ([]byte, []int) {
	return file_pkg_visibility_proto_events_proto_rawDescGZIP(), []int{24}
}

func (x *PodController) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PodController) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PodController) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pkg_visibility_proto_events_proto protoreflect.FileDescriptor

const file_pkg_visibility_proto_events_proto_rawDesc = "" +
	"\n" +
	"!pkg/visibility/proto/events.proto\x12Scom.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility\"\xbe\x04\n" +
	"\x0fAutoscalerEvent\x12|\n" +
	"\x06status\x18\x01 \x01(\v2b.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ClusterStatusH\x00R\x06status\x12\x80\x01\n" +
	"\bdecision\x18\x02 \x01(\v2b.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEventH\x00R\bdecision\x12\x82\x01\n" +
	"\vresult_info\x18\x03 \x01(\v2_.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ResultInfoH\x00R\n" +
	"resultInfo\x12\x95\x01\n" +
	"\x12no_decision_status\x18\x04 \x01(\v2e.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoDecisionStatusH\x00R\x10noDecisionStatusB\r\n" +
	"\vevent_oneof\"\xa6\x01\n" +
	"\rClusterStatus\x12!\n" +
	"\fmeasure_time\x18\x01 \x01(\x03R\vmeasureTime\x124\n" +
	"\x16autoscaled_nodes_count\x18\x02 \x01(\x05R\x14autoscaledNodesCount\x126\n" +
	"\x17autoscaled_nodes_target\x18\x03 \x01(\x05R\x15autoscaledNodesTargetJ\x04\b\x04\x10\x05\"\xab\x01\n" +
	"\n" +
	"ResultInfo\x12!\n" +
	"\fmeasure_time\x18\x01 \x01(\x03R\vmeasureTime\x12z\n" +
	"\aresults\x18\x02 \x03(\v2`.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.EventResultR\aresults\"\xb0\x01\n" +
	"\vEventResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x85\x01\n" +
	"\terror_msg\x18\x02 \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\berrorMsg\"\x94\x05\n" +
	"\rDecisionEvent\x12\x1f\n" +
	"\vdecide_time\x18\x01 \x01(\x03R\n" +
	"decideTime\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12}\n" +
	"\bscale_up\x18\n" +
	" \x01(\v2`.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpDataH\x00R\ascaleUp\x12\x83\x01\n" +
	"\n" +
	"scale_down\x18\v \x01(\v2b.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownDataH\x00R\tscaleDown\x12\x96\x01\n" +
	"\x11node_pool_created\x18\f \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolCreatedDataH\x00R\x0fnodePoolCreated\x12\x96\x01\n" +
	"\x11node_pool_deleted\x18\r \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolDeletedDataH\x00R\x0fnodePoolDeletedB\x10\n" +
	"\x0edecision_oneof\"\xd7\x02\n" +
	"\x10NoDecisionStatus\x12!\n" +
	"\fmeasure_time\x18\x01 \x01(\x03R\vmeasureTime\x12\x84\x01\n" +
	"\vno_scale_up\x18\n" +
	" \x01(\v2b.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpDataH\x00R\tnoScaleUp\x12\x8a\x01\n" +
	"\rno_scale_down\x18\v \x01(\v2d.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleDownDataH\x00R\vnoScaleDownB\f\n" +
	"\n" +
	"kind_oneof\"\xd9\x02\n" +
	"\vScaleUpData\x12\x86\x01\n" +
	"\x0eincreased_migs\x18\x01 \x03(\v2_.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpMigR\rincreasedMigs\x12\x81\x01\n" +
	"\x0ftriggering_pods\x18\n" +
	" \x03(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodR\x0etriggeringPods\x12=\n" +
	"\x1btriggering_pods_total_count\x18\v \x01(\x05R\x18triggeringPodsTotalCount\"\xa3\x01\n" +
	"\rScaleDownData\x12\x91\x01\n" +
	"\x13nodes_to_be_removed\x18\x01 \x03(\v2b.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownNodeR\x10nodesToBeRemoved\"\x99\x05\n" +
	"\rNoScaleUpData\x12\x80\x01\n" +
	"\x06reason\x18\x01 \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\x06reason\x12\x96\x01\n" +
	"\x12nap_failure_reason\x18\x02 \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\x10napFailureReason\x12\x9a\x01\n" +
	"\x14unhandled_pod_groups\x18\x03 \x03(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanationR\x12unhandledPodGroups\x12F\n" +
	" unhandled_pod_groups_total_count\x18\x04 \x01(\x05R\x1cunhandledPodGroupsTotalCount\x12\x86\x01\n" +
	"\fskipped_migs\x18\x05 \x03(\v2c.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanationR\vskippedMigs\"\xbc\x02\n" +
	"\x0fNoScaleDownData\x12\x80\x01\n" +
	"\x06reason\x18\x01 \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\x06reason\x12z\n" +
	"\x05nodes\x18\x02 \x03(\v2d.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeExplanationR\x05nodes\x12*\n" +
	"\x11nodes_total_count\x18\x04 \x01(\x05R\x0fnodesTotalCount\"\xc8\x01\n" +
	"\x13NodePoolCreatedData\x12|\n" +
	"\n" +
	"node_pools\x18\x01 \x03(\v2].com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolR\tnodePools\x123\n" +
	"\x16triggering_scale_up_id\x18\x02 \x01(\tR\x13triggeringScaleUpId\"=\n" +
	"\x13NodePoolDeletedData\x12&\n" +
	"\x0fnode_pool_names\x18\x01 \x03(\tR\rnodePoolNames\"\xa1\x01\n" +
	"\n" +
	"ScaleUpMig\x12j\n" +
	"\x03mig\x18\x01 \x01(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigR\x03mig\x12'\n" +
	"\x0frequested_nodes\x18\x02 \x01(\x05R\x0erequestedNodes\"\xef\x01\n" +
	"\tMigStatus\x12j\n" +
	"\x03mig\x18\x01 \x01(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigR\x03mig\x12\x1f\n" +
	"\vactual_size\x18\x02 \x01(\x05R\n" +
	"actualSize\x12\x1f\n" +
	"\vtarget_size\x18\x03 \x01(\x05R\n" +
	"targetSize\x12\x19\n" +
	"\bmin_size\x18\x04 \x01(\x05R\aminSize\x12\x19\n" +
	"\bmax_size\x18\x05 \x01(\x05R\amaxSize\"\xb4\x02\n" +
	"\rScaleDownNode\x12m\n" +
	"\x04node\x18\x01 \x01(\v2Y.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeR\x04node\x12{\n" +
	"\fevicted_pods\x18\x02 \x03(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodR\vevictedPods\x127\n" +
	"\x18evicted_pods_total_count\x18\x04 \x01(\x05R\x15evictedPodsTotalCount\"\xab\x01\n" +
	"\bPodGroup\x12w\n" +
	"\n" +
	"sample_pod\x18\x01 \x01(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodR\tsamplePod\x12&\n" +
	"\x0ftotal_pod_count\x18\x02 \x01(\x05R\rtotalPodCount\"\xc0\x04\n" +
	"\x13PodGroupExplanation\x12z\n" +
	"\tpod_group\x18\x01 \x01(\v2].com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupR\bpodGroup\x12\x88\x01\n" +
	"\rrejected_migs\x18\x02 \x03(\v2c.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanationR\frejectedMigs\x12\x98\x01\n" +
	"\x13nap_failure_reasons\x18\x03 \x03(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\x11napFailureReasons\x12\x86\x01\n" +
	"\fskipped_migs\x18\x04 \x03(\v2c.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanationR\vskippedMigs\"\x83\x02\n" +
	"\x0fNodeExplanation\x12m\n" +
	"\x04node\x18\x01 \x01(\v2Y.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeR\x04node\x12\x80\x01\n" +
	"\x06reason\x18\x02 \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\x06reason\"\xff\x01\n" +
	"\x0eMigExplanation\x12j\n" +
	"\x03mig\x18\x01 \x01(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigR\x03mig\x12\x80\x01\n" +
	"\x06reason\x18\x02 \x01(\v2h.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessageR\x06reason\"T\n" +
	"\x13ParametrizedMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\tR\n" +
	"parameters\"I\n" +
	"\x03Mig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bnodepool\x18\x02 \x01(\tR\bnodepool\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\"\x8c\x01\n" +
	"\bNodePool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12l\n" +
	"\x04migs\x18\x02 \x03(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigR\x04migs\"\xc0\x01\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12j\n" +
	"\x03mig\x18\x02 \x01(\v2X.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigR\x03mig\x12\x1b\n" +
	"\tcpu_ratio\x18\x03 \x01(\x05R\bcpuRatio\x12\x1b\n" +
	"\tmem_ratio\x18\x04 \x01(\x05R\bmemRatio\"\xbc\x01\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x82\x01\n" +
	"\n" +
	"controller\x18\x02 \x01(\v2b.com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodControllerR\n" +
	"controller\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"X\n" +
	"\rPodController\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB\x91\x01\n" +
	"Scom.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibilityB ClusterAutoscalerVisibilityProtoP\x01Z\x16./pkg/visibility/protob\x06proto3"

var (
	file_pkg_visibility_proto_events_proto_rawDescOnce sync.Once
	file_pkg_visibility_proto_events_proto_rawDescData []byte
)

func file_pkg_visibility_proto_events_proto_rawDescGZIP() []byte {
	file_pkg_visibility_proto_events_proto_rawDescOnce.Do(func() {
		file_pkg_visibility_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_visibility_proto_events_proto_rawDesc), len(file_pkg_visibility_proto_events_proto_rawDesc)))
	})
	return file_pkg_visibility_proto_events_proto_rawDescData
}

var file_pkg_visibility_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_visibility_proto_events_proto_goTypes = []any{
	(*AutoscalerEvent)(nil),     // 0: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.AutoscalerEvent
	(*ClusterStatus)(nil),       // 1: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ClusterStatus
	(*ResultInfo)(nil),          // 2: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ResultInfo
	(*EventResult)(nil),         // 3: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.EventResult
	(*DecisionEvent)(nil),       // 4: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEvent
	(*NoDecisionStatus)(nil),    // 5: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoDecisionStatus
	(*ScaleUpData)(nil),         // 6: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpData
	(*ScaleDownData)(nil),       // 7: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownData
	(*NoScaleUpData)(nil),       // 8: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpData
	(*NoScaleDownData)(nil),     // 9: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleDownData
	(*NodePoolCreatedData)(nil), // 10: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolCreatedData
	(*NodePoolDeletedData)(nil), // 11: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolDeletedData
	(*ScaleUpMig)(nil),          // 12: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpMig
	(*MigStatus)(nil),           // 13: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigStatus
	(*ScaleDownNode)(nil),       // 14: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownNode
	(*PodGroup)(nil),            // 15: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroup
	(*PodGroupExplanation)(nil), // 16: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanation
	(*NodeExplanation)(nil),     // 17: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeExplanation
	(*MigExplanation)(nil),      // 18: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanation
	(*ParametrizedMessage)(nil), // 19: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	(*Mig)(nil),                 // 20: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Mig
	(*NodePool)(nil),            // 21: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePool
	(*Node)(nil),                // 22: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Node
	(*Pod)(nil),                 // 23: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Pod
	(*PodController)(nil),       // 24: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodController
}
var file_pkg_visibility_proto_events_proto_depIdxs = []int32{
	1,  // 0: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.AutoscalerEvent.status:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ClusterStatus
	4,  // 1: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.AutoscalerEvent.decision:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEvent
	2,  // 2: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.AutoscalerEvent.result_info:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ResultInfo
	5,  // 3: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.AutoscalerEvent.no_decision_status:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoDecisionStatus
	3,  // 4: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ResultInfo.results:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.EventResult
	19, // 5: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.EventResult.error_msg:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	6,  // 6: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEvent.scale_up:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpData
	7,  // 7: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEvent.scale_down:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownData
	10, // 8: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEvent.node_pool_created:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolCreatedData
	11, // 9: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.DecisionEvent.node_pool_deleted:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolDeletedData
	8,  // 10: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoDecisionStatus.no_scale_up:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpData
	9,  // 11: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoDecisionStatus.no_scale_down:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleDownData
	12, // 12: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpData.increased_migs:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpMig
	23, // 13: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpData.triggering_pods:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Pod
	14, // 14: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownData.nodes_to_be_removed:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownNode
	19, // 15: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpData.reason:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	19, // 16: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpData.nap_failure_reason:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	16, // 17: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpData.unhandled_pod_groups:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanation
	18, // 18: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleUpData.skipped_migs:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanation
	19, // 19: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleDownData.reason:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	17, // 20: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NoScaleDownData.nodes:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeExplanation
	21, // 21: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePoolCreatedData.node_pools:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePool
	20, // 22: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleUpMig.mig:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Mig
	20, // 23: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigStatus.mig:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Mig
	22, // 24: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownNode.node:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Node
	23, // 25: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ScaleDownNode.evicted_pods:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Pod
	23, // 26: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroup.sample_pod:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Pod
	15, // 27: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanation.pod_group:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroup
	18, // 28: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanation.rejected_migs:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanation
	19, // 29: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanation.nap_failure_reasons:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	18, // 30: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodGroupExplanation.skipped_migs:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanation
	22, // 31: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeExplanation.node:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Node
	19, // 32: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodeExplanation.reason:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	20, // 33: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanation.mig:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Mig
	19, // 34: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.MigExplanation.reason:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.ParametrizedMessage
	20, // 35: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.NodePool.migs:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Mig
	20, // 36: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Node.mig:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Mig
	24, // 37: com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.Pod.controller:type_name -> com.google.cloud.boq.clientapi.resource.container.proto.clusterautoscalervisibility.PodController
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_pkg_visibility_proto_events_proto_init() }
func file_pkg_visibility_proto_events_proto_init() {
	if File_pkg_visibility_proto_events_proto != nil {
		return
	}
	file_pkg_visibility_proto_events_proto_msgTypes[0].OneofWrappers = []any{
		(*AutoscalerEvent_Status)(nil),
		(*AutoscalerEvent_Decision)(nil),
		(*AutoscalerEvent_ResultInfo)(nil),
		(*AutoscalerEvent_NoDecisionStatus)(nil),
	}
	file_pkg_visibility_proto_events_proto_msgTypes[4].OneofWrappers = []any{
		(*DecisionEvent_ScaleUp)(nil),
		(*DecisionEvent_ScaleDown)(nil),
		(*DecisionEvent_NodePoolCreated)(nil),
		(*DecisionEvent_NodePoolDeleted)(nil),
	}
	file_pkg_visibility_proto_events_proto_msgTypes[5].OneofWrappers = []any{
		(*NoDecisionStatus_NoScaleUp)(nil),
		(*NoDecisionStatus_NoScaleDown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_visibility_proto_events_proto_rawDesc), len(file_pkg_visibility_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_visibility_proto_events_proto_goTypes,
		DependencyIndexes: file_pkg_visibility_proto_events_proto_depIdxs,
		MessageInfos:      file_pkg_visibility_proto_events_proto_msgTypes,
	}.Build()
	File_pkg_visibility_proto_events_proto = out.File
	file_pkg_visibility_proto_events_proto_goTypes = nil
	file_pkg_visibility_proto_events_proto_depIdxs = nil
}
