//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Accelerator) DeepCopyInto(out *Accelerator) {
	*out = *in
	if in.Configurations != nil {
		in, out := &in.Configurations, &out.Configurations
		*out = make([]AcceleratorConfig, len(*in))
		copy(*out, *in)
	}
	if in.PartitionSizes != nil {
		in, out := &in.PartitionSizes, &out.PartitionSizes
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PreemptibleWeight != nil {
		in, out := &in.PreemptibleWeight, &out.PreemptibleWeight
		*out = new(string)
		**out = **in
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.Topologies != nil {
		in, out := &in.Topologies, &out.Topologies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MultiInstanceSharingSupported != nil {
		in, out := &in.MultiInstanceSharingSupported, &out.MultiInstanceSharingSupported
		*out = new(bool)
		**out = **in
	}
	if in.TimeSharingSupported != nil {
		in, out := &in.TimeSharingSupported, &out.TimeSharingSupported
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Accelerator.
func (in *Accelerator) DeepCopy() *Accelerator {
	if in == nil {
		return nil
	}
	out := new(Accelerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorConfig) DeepCopyInto(out *AcceleratorConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorConfig.
func (in *AcceleratorConfig) DeepCopy() *AcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(AcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorSpec) DeepCopyInto(out *AcceleratorSpec) {
	*out = *in
	if in.TpuConfig != nil {
		in, out := &in.TpuConfig, &out.TpuConfig
		*out = new(TpuConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorSpec.
func (in *AcceleratorSpec) DeepCopy() *AcceleratorSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootDiskConfig) DeepCopyInto(out *BootDiskConfig) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootDiskConfig.
func (in *BootDiskConfig) DeepCopy() *BootDiskConfig {
	if in == nil {
		return nil
	}
	out := new(BootDiskConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPlatform) DeepCopyInto(out *CPUPlatform) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vendor != nil {
		in, out := &in.Vendor, &out.Vendor
		*out = new(string)
		**out = **in
	}
	if in.VendorOrder != nil {
		in, out := &in.VendorOrder, &out.VendorOrder
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPlatform.
func (in *CPUPlatform) DeepCopy() *CPUPlatform {
	if in == nil {
		return nil
	}
	out := new(CPUPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompactPlacementConfig) DeepCopyInto(out *CompactPlacementConfig) {
	*out = *in
	if in.MaxCount != nil {
		in, out := &in.MaxCount, &out.MaxCount
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompactPlacementConfig.
func (in *CompactPlacementConfig) DeepCopy() *CompactPlacementConfig {
	if in == nil {
		return nil
	}
	out := new(CompactPlacementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialNodeConfig) DeepCopyInto(out *ConfidentialNodeConfig) {
	*out = *in
	if in.Supported != nil {
		in, out := &in.Supported, &out.Supported
		*out = new(bool)
		**out = **in
	}
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]ConfidentialNodeType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialNodeConfig.
func (in *ConfidentialNodeConfig) DeepCopy() *ConfidentialNodeConfig {
	if in == nil {
		return nil
	}
	out := new(ConfidentialNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialNodeType) DeepCopyInto(out *ConfidentialNodeType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialNodeType.
func (in *ConfidentialNodeType) DeepCopy() *ConfidentialNodeType {
	if in == nil {
		return nil
	}
	out := new(ConfidentialNodeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSSDConfig) DeepCopyInto(out *LocalSSDConfig) {
	*out = *in
	if in.AvailableCounts != nil {
		in, out := &in.AvailableCounts, &out.AvailableCounts
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSSDConfig.
func (in *LocalSSDConfig) DeepCopy() *LocalSSDConfig {
	if in == nil {
		return nil
	}
	out := new(LocalSSDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfig) DeepCopyInto(out *MachineConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfig.
func (in *MachineConfig) DeepCopy() *MachineConfig {
	if in == nil {
		return nil
	}
	out := new(MachineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigList) DeepCopyInto(out *MachineConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigList.
func (in *MachineConfigList) DeepCopy() *MachineConfigList {
	if in == nil {
		return nil
	}
	out := new(MachineConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigSpec) DeepCopyInto(out *MachineConfigSpec) {
	*out = *in
	in.MachineFamily.DeepCopyInto(&out.MachineFamily)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigSpec.
func (in *MachineConfigSpec) DeepCopy() *MachineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigStatus) DeepCopyInto(out *MachineConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigStatus.
func (in *MachineConfigStatus) DeepCopy() *MachineConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineFamily) DeepCopyInto(out *MachineFamily) {
	*out = *in
	if in.UsagePolicy != nil {
		in, out := &in.UsagePolicy, &out.UsagePolicy
		*out = new(UsagePolicy)
		(*in).DeepCopyInto(*out)
	}
	in.DefaultProperties.DeepCopyInto(&out.DefaultProperties)
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = new(MachineFamilyWeights)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineTypes != nil {
		in, out := &in.MachineTypes, &out.MachineTypes
		*out = make([]MachineType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]Accelerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputeClasses != nil {
		in, out := &in.ComputeClasses, &out.ComputeClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PageType != nil {
		in, out := &in.PageType, &out.PageType
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineFamily.
func (in *MachineFamily) DeepCopy() *MachineFamily {
	if in == nil {
		return nil
	}
	out := new(MachineFamily)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineFamilyWeights) DeepCopyInto(out *MachineFamilyWeights) {
	*out = *in
	out.Predefined = in.Predefined
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(ResourceWeights)
		**out = **in
	}
	if in.Preemptible != nil {
		in, out := &in.Preemptible, &out.Preemptible
		*out = new(ResourceWeights)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineFamilyWeights.
func (in *MachineFamilyWeights) DeepCopy() *MachineFamilyWeights {
	if in == nil {
		return nil
	}
	out := new(MachineFamilyWeights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineProperties) DeepCopyInto(out *MachineProperties) {
	*out = *in
	if in.SystemArchitecture != nil {
		in, out := &in.SystemArchitecture, &out.SystemArchitecture
		*out = new(string)
		**out = **in
	}
	if in.CPUPlatforms != nil {
		in, out := &in.CPUPlatforms, &out.CPUPlatforms
		*out = make([]CPUPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompactPlacementConfig != nil {
		in, out := &in.CompactPlacementConfig, &out.CompactPlacementConfig
		*out = new(CompactPlacementConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ThreadsPerCore != nil {
		in, out := &in.ThreadsPerCore, &out.ThreadsPerCore
		*out = new(int64)
		**out = **in
	}
	if in.BootDiskConfig != nil {
		in, out := &in.BootDiskConfig, &out.BootDiskConfig
		*out = new(BootDiskConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentDiskTypeConfigs != nil {
		in, out := &in.PersistentDiskTypeConfigs, &out.PersistentDiskTypeConfigs
		*out = make([]PersistentDiskTypeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NAPDisabled != nil {
		in, out := &in.NAPDisabled, &out.NAPDisabled
		*out = new(bool)
		**out = **in
	}
	if in.SupportsConfidentialNodes != nil {
		in, out := &in.SupportsConfidentialNodes, &out.SupportsConfidentialNodes
		*out = new(bool)
		**out = **in
	}
	if in.ConfidentialNodeConfig != nil {
		in, out := &in.ConfidentialNodeConfig, &out.ConfidentialNodeConfig
		*out = new(ConfidentialNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineProperties.
func (in *MachineProperties) DeepCopy() *MachineProperties {
	if in == nil {
		return nil
	}
	out := new(MachineProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineResources) DeepCopyInto(out *MachineResources) {
	*out = *in
	if in.LocalSSDConfig != nil {
		in, out := &in.LocalSSDConfig, &out.LocalSSDConfig
		*out = new(LocalSSDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Accelerator != nil {
		in, out := &in.Accelerator, &out.Accelerator
		*out = new(AcceleratorSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineResources.
func (in *MachineResources) DeepCopy() *MachineResources {
	if in == nil {
		return nil
	}
	out := new(MachineResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineType) DeepCopyInto(out *MachineType) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = new(MachineTypeWeights)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(MachineProperties)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineType.
func (in *MachineType) DeepCopy() *MachineType {
	if in == nil {
		return nil
	}
	out := new(MachineType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineTypeWeights) DeepCopyInto(out *MachineTypeWeights) {
	*out = *in
	if in.InstanceWeight != nil {
		in, out := &in.InstanceWeight, &out.InstanceWeight
		*out = new(string)
		**out = **in
	}
	if in.PreemptibleInstanceWeight != nil {
		in, out := &in.PreemptibleInstanceWeight, &out.PreemptibleInstanceWeight
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineTypeWeights.
func (in *MachineTypeWeights) DeepCopy() *MachineTypeWeights {
	if in == nil {
		return nil
	}
	out := new(MachineTypeWeights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentDiskTypeConfig) DeepCopyInto(out *PersistentDiskTypeConfig) {
	*out = *in
	if in.ConfidentialMode != nil {
		in, out := &in.ConfidentialMode, &out.ConfidentialMode
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentDiskTypeConfig.
func (in *PersistentDiskTypeConfig) DeepCopy() *PersistentDiskTypeConfig {
	if in == nil {
		return nil
	}
	out := new(PersistentDiskTypeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceWeights) DeepCopyInto(out *ResourceWeights) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceWeights.
func (in *ResourceWeights) DeepCopy() *ResourceWeights {
	if in == nil {
		return nil
	}
	out := new(ResourceWeights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TpuConfig) DeepCopyInto(out *TpuConfig) {
	*out = *in
	if in.SingleHostTopology != nil {
		in, out := &in.SingleHostTopology, &out.SingleHostTopology
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TpuConfig.
func (in *TpuConfig) DeepCopy() *TpuConfig {
	if in == nil {
		return nil
	}
	out := new(TpuConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsagePolicy) DeepCopyInto(out *UsagePolicy) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsagePolicy.
func (in *UsagePolicy) DeepCopy() *UsagePolicy {
	if in == nil {
		return nil
	}
	out := new(UsagePolicy)
	in.DeepCopyInto(out)
	return out
}
