// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	cloudgooglecomv1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/client/applyconfiguration/cloud.google.com/v1"
	v1 "k8s.io/gke-autoscaling/cluster-autoscaler/apis/machineconfig/cloud.google.com/v1"
)

// FakeMachineConfigs implements MachineConfigInterface
type FakeMachineConfigs struct {
	Fake *FakeCloudV1
}

var machineconfigsResource = v1.SchemeGroupVersion.WithResource("machineconfigs")

var machineconfigsKind = v1.SchemeGroupVersion.WithKind("MachineConfig")

// Get takes name of the machineConfig, and returns the corresponding machineConfig object, and an error if there is any.
func (c *FakeMachineConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MachineConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(machineconfigsResource, name), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}

// List takes label and field selectors, and returns the list of MachineConfigs that match those selectors.
func (c *FakeMachineConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MachineConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(machineconfigsResource, machineconfigsKind, opts), &v1.MachineConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.MachineConfigList{ListMeta: obj.(*v1.MachineConfigList).ListMeta}
	for _, item := range obj.(*v1.MachineConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineConfigs.
func (c *FakeMachineConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(machineconfigsResource, opts))
}

// Create takes the representation of a machineConfig and creates it.  Returns the server's representation of the machineConfig, and an error, if there is any.
func (c *FakeMachineConfigs) Create(ctx context.Context, machineConfig *v1.MachineConfig, opts metav1.CreateOptions) (result *v1.MachineConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(machineconfigsResource, machineConfig), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}

// Update takes the representation of a machineConfig and updates it. Returns the server's representation of the machineConfig, and an error, if there is any.
func (c *FakeMachineConfigs) Update(ctx context.Context, machineConfig *v1.MachineConfig, opts metav1.UpdateOptions) (result *v1.MachineConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(machineconfigsResource, machineConfig), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMachineConfigs) UpdateStatus(ctx context.Context, machineConfig *v1.MachineConfig, opts metav1.UpdateOptions) (*v1.MachineConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(machineconfigsResource, "status", machineConfig), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}

// Delete takes name of the machineConfig and deletes it. Returns an error if one occurs.
func (c *FakeMachineConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(machineconfigsResource, name, opts), &v1.MachineConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(machineconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.MachineConfigList{})
	return err
}

// Patch applies the patch and returns the patched machineConfig.
func (c *FakeMachineConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MachineConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(machineconfigsResource, name, pt, data, subresources...), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied machineConfig.
func (c *FakeMachineConfigs) Apply(ctx context.Context, machineConfig *cloudgooglecomv1.MachineConfigApplyConfiguration, opts metav1.ApplyOptions) (result *v1.MachineConfig, err error) {
	if machineConfig == nil {
		return nil, fmt.Errorf("machineConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(machineConfig)
	if err != nil {
		return nil, err
	}
	name := machineConfig.Name
	if name == nil {
		return nil, fmt.Errorf("machineConfig.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(machineconfigsResource, *name, types.ApplyPatchType, data), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeMachineConfigs) ApplyStatus(ctx context.Context, machineConfig *cloudgooglecomv1.MachineConfigApplyConfiguration, opts metav1.ApplyOptions) (result *v1.MachineConfig, err error) {
	if machineConfig == nil {
		return nil, fmt.Errorf("machineConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(machineConfig)
	if err != nil {
		return nil, err
	}
	name := machineConfig.Name
	if name == nil {
		return nil, fmt.Errorf("machineConfig.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(machineconfigsResource, *name, types.ApplyPatchType, data, "status"), &v1.MachineConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.MachineConfig), err
}
