// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/apis/nodemanagement.gke.io/v1alpha1"
)

// UpdateInfoLister helps list UpdateInfos.
// All objects returned here must be treated as read-only.
type UpdateInfoLister interface {
	// List lists all UpdateInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.UpdateInfo, err error)
	// UpdateInfos returns an object that can list and get UpdateInfos.
	UpdateInfos(namespace string) UpdateInfoNamespaceLister
	UpdateInfoListerExpansion
}

// updateInfoLister implements the UpdateInfoLister interface.
type updateInfoLister struct {
	indexer cache.Indexer
}

// NewUpdateInfoLister returns a new UpdateInfoLister.
func NewUpdateInfoLister(indexer cache.Indexer) UpdateInfoLister {
	return &updateInfoLister{indexer: indexer}
}

// List lists all UpdateInfos in the indexer.
func (s *updateInfoLister) List(selector labels.Selector) (ret []*v1alpha1.UpdateInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.UpdateInfo))
	})
	return ret, err
}

// UpdateInfos returns an object that can list and get UpdateInfos.
func (s *updateInfoLister) UpdateInfos(namespace string) UpdateInfoNamespaceLister {
	return updateInfoNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// UpdateInfoNamespaceLister helps list and get UpdateInfos.
// All objects returned here must be treated as read-only.
type UpdateInfoNamespaceLister interface {
	// List lists all UpdateInfos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.UpdateInfo, err error)
	// Get retrieves the UpdateInfo from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.UpdateInfo, error)
	UpdateInfoNamespaceListerExpansion
}

// updateInfoNamespaceLister implements the UpdateInfoNamespaceLister
// interface.
type updateInfoNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all UpdateInfos in the indexer for a given namespace.
func (s updateInfoNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.UpdateInfo, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.UpdateInfo))
	})
	return ret, err
}

// Get retrieves the UpdateInfo from the indexer for a given namespace and name.
func (s updateInfoNamespaceLister) Get(name string) (*v1alpha1.UpdateInfo, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("updateinfo"), name)
	}
	return obj.(*v1alpha1.UpdateInfo), nil
}
