// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityProvisionPolicy) DeepCopyInto(out *CapacityProvisionPolicy) {
	*out = *in
	if in.PodsToReplace != nil {
		in, out := &in.PodsToReplace, &out.PodsToReplace
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityProvisionPolicy.
func (in *CapacityProvisionPolicy) DeepCopy() *CapacityProvisionPolicy {
	if in == nil {
		return nil
	}
	out := new(CapacityProvisionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityRequest) DeepCopyInto(out *CapacityRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityRequest.
func (in *CapacityRequest) DeepCopy() *CapacityRequest {
	if in == nil {
		return nil
	}
	out := new(CapacityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityRequestCondition) DeepCopyInto(out *CapacityRequestCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityRequestCondition.
func (in *CapacityRequestCondition) DeepCopy() *CapacityRequestCondition {
	if in == nil {
		return nil
	}
	out := new(CapacityRequestCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityRequestList) DeepCopyInto(out *CapacityRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityRequestList.
func (in *CapacityRequestList) DeepCopy() *CapacityRequestList {
	if in == nil {
		return nil
	}
	out := new(CapacityRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityRequestSpec) DeepCopyInto(out *CapacityRequestSpec) {
	*out = *in
	in.Capacity.DeepCopyInto(&out.Capacity)
	in.ProvisionPolicy.DeepCopyInto(&out.ProvisionPolicy)
	if in.ProvisionedCapacitySelector != nil {
		in, out := &in.ProvisionedCapacitySelector, &out.ProvisionedCapacitySelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityRequestSpec.
func (in *CapacityRequestSpec) DeepCopy() *CapacityRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CapacityRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityRequestStatus) DeepCopyInto(out *CapacityRequestStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CapacityRequestCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityRequestStatus.
func (in *CapacityRequestStatus) DeepCopy() *CapacityRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityRequestStatus)
	in.DeepCopyInto(out)
	return out
}
