// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/client/listers/nodemanagement.gke.io/v1alpha1 (interfaces: UpdateInfoLister,UpdateInfoListerExpansion)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	labels "k8s.io/apimachinery/pkg/labels"
	v1alpha1 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/apis/nodemanagement.gke.io/v1alpha1"
	v1alpha10 "k8s.io/gke-autoscaling/cluster-autoscaler/pkg/updateinfos/client/listers/nodemanagement.gke.io/v1alpha1"
)

// MockUpdateInfoLister is a mock of UpdateInfoLister interface.
type MockUpdateInfoLister struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateInfoListerMockRecorder
}

// MockUpdateInfoListerMockRecorder is the mock recorder for MockUpdateInfoLister.
type MockUpdateInfoListerMockRecorder struct {
	mock *MockUpdateInfoLister
}

// NewMockUpdateInfoLister creates a new mock instance.
func NewMockUpdateInfoLister(ctrl *gomock.Controller) *MockUpdateInfoLister {
	mock := &MockUpdateInfoLister{ctrl: ctrl}
	mock.recorder = &MockUpdateInfoListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateInfoLister) EXPECT() *MockUpdateInfoListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockUpdateInfoLister) List(arg0 labels.Selector) ([]*v1alpha1.UpdateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*v1alpha1.UpdateInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUpdateInfoListerMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUpdateInfoLister)(nil).List), arg0)
}

// UpdateInfos mocks base method.
func (m *MockUpdateInfoLister) UpdateInfos(arg0 string) v1alpha10.UpdateInfoNamespaceLister {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInfos", arg0)
	ret0, _ := ret[0].(v1alpha10.UpdateInfoNamespaceLister)
	return ret0
}

// UpdateInfos indicates an expected call of UpdateInfos.
func (mr *MockUpdateInfoListerMockRecorder) UpdateInfos(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInfos", reflect.TypeOf((*MockUpdateInfoLister)(nil).UpdateInfos), arg0)
}

// MockUpdateInfoListerExpansion is a mock of UpdateInfoListerExpansion interface.
type MockUpdateInfoListerExpansion struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateInfoListerExpansionMockRecorder
}

// MockUpdateInfoListerExpansionMockRecorder is the mock recorder for MockUpdateInfoListerExpansion.
type MockUpdateInfoListerExpansionMockRecorder struct {
	mock *MockUpdateInfoListerExpansion
}

// NewMockUpdateInfoListerExpansion creates a new mock instance.
func NewMockUpdateInfoListerExpansion(ctrl *gomock.Controller) *MockUpdateInfoListerExpansion {
	mock := &MockUpdateInfoListerExpansion{ctrl: ctrl}
	mock.recorder = &MockUpdateInfoListerExpansionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateInfoListerExpansion) EXPECT() *MockUpdateInfoListerExpansionMockRecorder {
	return m.recorder
}
