// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package machinetypes

import (
	"fmt"

	resourceapi "k8s.io/api/resource/v1"
	"k8s.io/gke-autoscaling/cluster-autoscaler/pkg/cloudprovider/gke/dynamicresources/dranet"
	"k8s.io/utils/ptr"
)

type dynamicDeviceAttribute func(nicIdx int) resourceapi.DeviceAttribute

// NicGroupConfig describes a group of NICs with a specific configuration.
type NicGroupConfig struct {
	// NicCount is the number of NICs in this group.
	NicCount int64
	// StaticAttributes are attributes that have a constant value for all NICs in this group.
	StaticAttributes map[resourceapi.QualifiedName]resourceapi.DeviceAttribute
	// DynamicAttributes are attributes whose values are generated by a function of the NIC's index in this group.
	DynamicAttributes map[resourceapi.QualifiedName]dynamicDeviceAttribute
}

// MultiNicConfig configs the attributes for the machine type's multi-NICs.
type MultiNicConfig struct {
	// SharedAttributes are attributes common to all NICs for this machine type.
	SharedAttributes map[resourceapi.QualifiedName]resourceapi.DeviceAttribute
	// NicGroups contain a slice of NicGroupConfig for NIC group configurations.
	NicGroups []NicGroupConfig
}

type DranetConfigProvider struct {
	configs map[string]MultiNicConfig
}

func NewDranetConfigProvider() DranetConfigProvider {
	defaultConfig := map[string]MultiNicConfig{
		// A3
		"a3-highgpu-8g":         a3HighgpunNicAttributes,
		"a3-edgegpu-8g":         a3EdgegpunNicAttributes,
		"a3-megagpu-8g":         a3MegagpuNicAttributes,
		"a3-edgegpu-8g-nolssd":  a3EdgegpunNicAttributes,
		"a3-ultragpu-8g":        a3UltragpuNicAttributes,
		"a3-ultragpu-8g-nolssd": a3UltragpuNicAttributes,
		// A4 & A4X
		"a4-highgpu-8g":         a4HighgpuNicAttributes,
		"a4-highgpu-8g-nolssd":  a4HighgpuNicAttributes,
		"a4x-highgpu-4g":        a4xHighgpuNicAttributes,
		"a4x-highgpu-4g-nolssd": a4xHighgpuNicAttributes,
		"a4x-maxgpu-4g-metal":   a4xMaxgpuMetalNicAttributes,
		// CT6E
		"ct6e-standard-1t": ct6eStandard1tNicAttributes,
		"ct6e-standard-4t": ct6eStandard4tNicAttributes,
		"ct6e-standard-8t": ct6eStandard8tNicAttributes,
		// TPU7 & TPU7X
		"tpu7-standard-4t":  tpu7StandardNicAttributes,
		"tpu7x-standard-4t": tpu7xStandardNicAttributes,
	}

	return DranetConfigProvider{configs: defaultConfig}
}

func NewDranetConfigProviderWithConfigs(configs map[string]MultiNicConfig) DranetConfigProvider {
	return DranetConfigProvider{configs: configs}
}

func (p DranetConfigProvider) ConfigForMachineType(machineType string) (MultiNicConfig, bool) {
	config, found := p.configs[machineType]
	return config, found
}

var (
	// a3-highgpu-8g
	a3HighgpunNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8244),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(true),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 4,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// a3-edgegpu-8g
	// a3-edgegpu-8g-nolssd
	a3EdgegpunNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8244),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(true),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 4,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// a3-megagpu-8g
	a3MegagpuNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8244),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(true),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 8,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// a3-ultragpu-8g
	// a3-ultragpu-8g-nolssd
	a3UltragpuNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU: IntAttrValue(8896),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 1,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
					dranet.AttrEBPF:            BoolAttrValue(true),
					dranet.AttrRDMA:            BoolAttrValue(false),
					dranet.AttrTCFilterNames:   StringAttrValue(""),
					dranet.AttrTCXProgramNames: StringAttrValue(""),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
			{
				NicCount: 8,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor: StringAttrValue("Mellanox Technologies"),
					dranet.AttrEBPF:      BoolAttrValue(false),
					dranet.AttrRDMA:      BoolAttrValue(true),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("gpu%drdma0", nicIdx))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-rdma-%v", nicIdx))
					},
				},
			},
		},
	}
	// a4-highgpu-8g
	// a4-highgpu-8g-lowmem
	a4HighgpuNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU: IntAttrValue(8896),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 1,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
					dranet.AttrEBPF:            BoolAttrValue(true),
					dranet.AttrRDMA:            BoolAttrValue(false),
					dranet.AttrTCFilterNames:   StringAttrValue(""),
					dranet.AttrTCXProgramNames: StringAttrValue(""),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
			{
				NicCount: 8,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor: StringAttrValue("Mellanox Technologies"),
					dranet.AttrEBPF:      BoolAttrValue(false),
					dranet.AttrRDMA:      BoolAttrValue(true),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("gpu%drdma0", nicIdx))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-rdma-%v", nicIdx))
					},
				},
			},
		},
	}
	// a4x-highgpu-4g
	// a4x-highgpu-4g-nolssd
	a4xHighgpuNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU: IntAttrValue(8896),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 1,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
					dranet.AttrEBPF:            BoolAttrValue(true),
					dranet.AttrRDMA:            BoolAttrValue(false),
					dranet.AttrTCFilterNames:   StringAttrValue(""),
					dranet.AttrTCXProgramNames: StringAttrValue(""),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
			{
				NicCount: 4,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor: StringAttrValue("Mellanox Technologies"),
					dranet.AttrEBPF:      BoolAttrValue(false),
					dranet.AttrRDMA:      BoolAttrValue(true),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("gpu%drdma0", nicIdx))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-rdma-%v", nicIdx))
					},
				},
			},
		},
	}
	// a4x-maxgpu-4g-metal
	a4xMaxgpuMetalNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU: IntAttrValue(8896),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 1,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrPCIVendor:       StringAttrValue("Intel Corporation"),
					dranet.AttrEBPF:            BoolAttrValue(false),
					dranet.AttrRDMA:            BoolAttrValue(false),
					dranet.AttrTCFilterNames:   StringAttrValue(""),
					dranet.AttrTCXProgramNames: StringAttrValue(""),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
			{
				NicCount: 8,
				StaticAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
					dranet.AttrEBPF:            BoolAttrValue(true),
					dranet.AttrRDMA:            BoolAttrValue(true),
					dranet.AttrTCFilterNames:   StringAttrValue(""),
					dranet.AttrTCXProgramNames: StringAttrValue("cil_from_netdev,cil_to_netdev"),
				},
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("gpu%dipvlan%d", nicIdx/2, nicIdx%2))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-rdma-%v", nicIdx))
					},
				},
			},
		},
	}
	// ct6e-standard-1t
	ct6eStandard1tNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8896),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(true),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 1,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// ct6e-standard-4t
	ct6eStandard4tNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8896),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(true),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 2,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// ct6e-standard-8t
	ct6eStandard8tNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8896),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(true),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 4,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// tpu7-standard-4t
	tpu7StandardNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8896),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(false),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 4,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
	// tpu7x-standard-4t
	tpu7xStandardNicAttributes = MultiNicConfig{
		SharedAttributes: map[resourceapi.QualifiedName]resourceapi.DeviceAttribute{
			dranet.AttrMTU:             IntAttrValue(8896),
			dranet.AttrPCIVendor:       StringAttrValue("Google, Inc."),
			dranet.AttrEBPF:            BoolAttrValue(false),
			dranet.AttrRDMA:            BoolAttrValue(false),
			dranet.AttrTCFilterNames:   StringAttrValue(""),
			dranet.AttrTCXProgramNames: StringAttrValue(""),
		},
		NicGroups: []NicGroupConfig{
			{
				NicCount: 2,
				DynamicAttributes: map[resourceapi.QualifiedName]dynamicDeviceAttribute{
					dranet.AttrInterfaceName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("eth%d", nicIdx+1))
					},
					dranet.GceAttrNetworkName: func(nicIdx int) resourceapi.DeviceAttribute {
						return StringAttrValue(fmt.Sprintf("additional-network-default-%v", nicIdx))
					},
				},
			},
		},
	}
)

// BoolAttrValue creates a DeviceAttribute with a boolean value
func BoolAttrValue(v bool) resourceapi.DeviceAttribute {
	return resourceapi.DeviceAttribute{
		BoolValue: ptr.To(v),
	}
}

// IntAttrValue creates a DeviceAttribute with an integer value
func IntAttrValue(v int64) resourceapi.DeviceAttribute {
	return resourceapi.DeviceAttribute{
		IntValue: ptr.To(v),
	}
}

// StringAttrValue creates a DeviceAttribute with a string value
func StringAttrValue(v string) resourceapi.DeviceAttribute {
	return resourceapi.DeviceAttribute{
		StringValue: ptr.To(v),
	}
}
